### ISSUE TITLE
spring cloud config server with mutilples repositories

### ISSUE THREAD

**Issue by gobedson** [spring-cloud/spring-cloud-config#886] opened 2018-01-16 14:55 UTC
Hi I'm trying to implement spring cloud config server but it's not working like i want when it come to multiples repositories.

here a is config server application.yml

# Application.yml
    spring:
     cloud:
      config:
       server:
         git:
          uri: http://git/data/config-repos-common.git
          username: user
          password: pwd
          force-pull: true
          clone-on-start: true
          repos:
            config-repos-pilot:
                pattern:  config-repos-pilot-*,api-sales-*,api-users-*'
                clone-on-start: true
                force-pull: true
                uri: http://git/data/config-repos-pilot.git
                username: user
                password: pwd
            config-repos-cross-canal:
                pattern : api-customer-profile-customers-*
                clone-on-start: true
                force-pull: true
                uri: http://git/data/config-repos-cross-canal.git
                username: user
                password: pwd

- In the common repository i have a folder name api-test-v1 which content application-local.yml and application-dev.yml

- In config-repos-pilot i have others folders and same for config-repos-cross-canal

When I start my application i can see my properties files for the common repot : http://localhost:9002/api-test-v1/local
in my tmp repo, all the repos are cloned but when i type http://localhost:9002/api-users-v1/local to see the files it's empty , the pattern not matching.

can anyone help me please ?

**Comment by spencergibb** [comment] 2018-01-16 15:27
This feature is not implemented

**Comment by gobedson** [comment] 2018-01-16 15:34
@spencergibb  thank you but how can I implement spring cloud config server if I've multiples teams and each of them have it own git repo with multiples api configs repos inside the git repos
# ALLTEAM:
  # common git repo
Team A
  # gitA:
     # api-repo
        # application-local.yml, application-dev.yml , application-prod.yml
Team B
  # gitB:
     # api-repo
        # application-local.yml, application-dev.yml , application-prod.yml

**Comment by spencergibb** [comment] 2018-01-30 00:38
> This feature is not implemented

**Comment by spencergibb** [comment] 2018-01-30 00:39
Duplicate of #855

**Closed by spencergibb** 2018-01-30 00:39 UTC
