### ISSUE TITLE
Cannot refresh configs in @FeignClient with @RefreshScope

### ISSUE THREAD

**Issue by masoudsafa** [spring-cloud/spring-cloud-config#848] opened 2017-11-14 13:45 UTC
I'm running a Spring Config Server and another Spring boot app that uses config server. I have a Feign-Client in my second app like this:

```java
@FeignClient(url = "${myconfig.url}", name = "ConfigServerFeign",
        configuration = {FeignConfig.class}, fallback = ConfigServerFeignFallback.class)
public interface ConfigServerFeign
{
    @RequestMapping(value = "/test", method = RequestMethod.POST,
            headers = {"Content-Type=application/json; charset=UTF-8"}, consumes = {MediaType.APPLICATION_JSON_UTF8_VALUE})
    RequestModel test(@RequestBody RequestModel request);
}
```

and i have a config class for feign like this:

```java
@Configuration
public class FeignConfig
{
    @Value("${myconfig.header}")
    private String authorization;
    @Bean
    public RequestInterceptor basicAuthRequestInterceptor()
    {
        return requestTemplate -> requestTemplate.header("Authorization", "Basic " + authorization);
    }
}
```

i need to change ${myconfig.url} or ${myconfig.header} in runtime. i think i have two option, first one is using @RefreshScope on top of ConfigServerConfig that does not work, the second option is to use @RefreshScope on FeignConfig class that gives me this error:

```java
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.example.configclient.ConfigServerFeign': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: No Scope registered for scope name 'refresh'
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1634) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:254) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1316) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1282) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1101) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    ... 19 common frames omitted
Caused by: java.lang.IllegalStateException: No Scope registered for scope name 'refresh'
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:337) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:372) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:116) ~[spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
    at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:85) ~[spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
    at org.springframework.cloud.context.named.NamedContextFactory.getInstance(NamedContextFactory.java:121) ~[spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
    at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.get(FeignClientFactoryBean.java:127) ~[spring-cloud-netflix-core-1.3.5.RELEASE.jar:1.3.5.RELEASE]
    at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.feign(FeignClientFactoryBean.java:84) ~[spring-cloud-netflix-core-1.3.5.RELEASE.jar:1.3.5.RELEASE]
    at org.springframework.cloud.netflix.feign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:155) ~[spring-cloud-netflix-core-1.3.5.RELEASE.jar:1.3.5.RELEASE]
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
    ... 29 common frames omitted
```

how can i fix this ??? :-(

**Comment by spencergibb** [comment] 2017-11-14 13:48
I would use `@CongurationProperties` instead of `@Value`.

**Comment by minorpoet** [comment] 2018-04-03 11:46
i face with this problem too,
@FeignClient(name="balabala" , url = "${myconfig.url}") ;   i want to refresh the "url"     but @RefreshScope doesn't work 

version Edgware.SR2

**Comment by minorpoet** [comment] 2018-04-04 07:39
@ryanjbaxter  i thought they are different scenes,   config class  annotated with  @CongurationProperties   or  @value +  @RefreshScope  can be refreshed on the fly ,like 
`
@CongurationProperties(prefix="url")
@Data
public class UrlConfig{
     private String shop; 
}

@RefreshScope
@Data
public class UrlConfig{
     @Value("url.shop")
     private String shop; 
}
`
both can be refreshed on the fly ,  but  @Feignclient(name="balabala" , url = "${myconfig.url}") placeholder  is in the annotation , i don't know how to mark it refreshable  ,      or  the inner HardCodedTarget refreshable or the proxy client refreshed ... etc

**Comment by ryanjbaxter** [comment] 2018-04-04 13:46
Please provide an app that reproduces the issue and we will take a look.

**Comment by minorpoet** [comment] 2018-04-08 06:37
sorry be absent  , it was Tomb-Sweeping Day in china,  we got 3 days off

here is my demo show this case :  
  https://github.com/minorpoet/feignclient-url-not-refresh

**Comment by minorpoet** [comment] 2018-04-11 06:30
any response ?

**Comment by ryanjbaxter** [comment] 2018-04-11 15:02
Can you please simplify your sample?  All those components should not be needed based on the description of the problem.

**Comment by BastiOfBerlin** [comment] 2018-04-12 18:47
I think I stumbled into the same problem and prepared a quite simple example: https://github.com/BastiOfBerlin/feignclient-refreshscope-problem

I change the URL after the EmbeddedServletContainer has been initialized. In my real app, I need to access the (randomly selected) port number to change the url property.
I then refresh the scope. Unfortunately, the FeignClient seems to be already initialized and does not get refreshed.

**Comment by spencergibb** [comment] 2018-04-12 19:06
@BastiOfBerlin wouldn't it be simpler to use ribbon in that case. The url field was never meant to be updated.

**Comment by BastiOfBerlin** [comment] 2018-04-13 08:32
In this demo, definitely.

But I have to implement sort of a loopback to the exact same microservice. Using `client.api-url=${server.port}` in the config doesn't work either. So I came up with the idea of waiting until the servlet container came up and set the config value to `'"http://localhost:" + localServerPort'`.

If ribbon could do that, I'd be happy, but have no idea on how to implement that.

I guess there's no way to re-initialize all or specific FeignClients?

**Comment by minorpoet** [comment] 2018-04-16 09:36
but,  lacking of these components   spring cloud config with bus won't work

**Comment by ryanjbaxter** [comment] 2018-04-16 18:28
@minorpoet 

> but, lacking of these components spring cloud config with bus won't work

what does this mean?

**Comment by minorpoet** [comment] 2018-04-17 14:03
i mean,  i  need git repo and mq to support notifying config changing event  to  spring cloud config consumer;   if not using mq and bus,  git repo is needed at least  and refresh config consumer directly through  {consumer-host}:{port}/refresh

**Comment by ryanjbaxter** [comment] 2018-04-17 15:29
@minorpoet not sure what those components have to do with the problem.  As @spencergibb said the `url` field is not meant to be refreshed.  You can instead use Ribbon and set `client.ribbon.listOfServers`.  When that property is updated and a refresh is performed than the Feign client should use the new property.

**Comment by minorpoet** [comment] 2018-04-18 15:39
but my target url  is php server,  not registered in eureka; while the config consumer is resigtered

**Comment by odedia** [comment] 2018-06-06 17:49
I am facing a similar issue with the "name" attribute. I'd like to be able to replace the eureka service ID that I am using at runtime without restarting the application. Instead of calling target-ms-v1, I want to call target-ms-v2. However, since "name" is in an annotation attribute it cannot be refreshed at runtime.

I there a way to use code to define the feign client instead of doing it with @FeignClient? That way I might be able to use @RefreshScope myself.

**Comment by spencergibb** [comment] 2018-06-06 17:51
There is a section in the docs about creating feign clients manually

**Comment by odedia** [comment] 2018-06-06 17:56
Thanks Spencer, I'll check it out!

So just to clarify - you do not see a way to refresh the name attribute via @RefreshScope (or other means), correct?

**Comment by spencergibb** [comment] 2018-06-06 17:57
No there is not.

**Comment by sj853** [comment] 2018-09-06 02:11
@minorpoet 我也有相同的疑问 兄弟你解决了吗

**Comment by fcjreed** [comment] 2018-09-19 20:52
Sorry to hijack the issue. I have a question that's related to this problem but has more to do with using refresh scope on the override beans we can provide in the configuration, e.g Logging.Level, Request.Options. You cannot put @RefreshScope on these beans either as it gives the same error. Does the provided solution of using the property "feign.client.config.feignName.readTimeout" apply dynamic values if changed in config server?

**Comment by minorpoet** [comment] 2018-09-29 17:29
@sj853  没呢，github通知没注意~~    现在才看到

**Comment by spring-issuemaster** [comment] 2018-10-02 17:00
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Closed by spring-issuemaster** 2018-10-02 17:00 UTC
Labels: question

**Comment by cens7** [comment] 2020-08-14 08:11
I have same question. Two years passed, did this question solved?

**Comment by hoseinit** [comment] 2020-10-06 12:53
I am also looking forward for a way to refresh feign when url has been changed and it's in RefreshScope

**Comment by tbw777** [comment] 2022-03-28 08:04
its of current interests
