### ISSUE TITLE
contention issue in org.springframework.cloud.config.server.resource.ResourceController.retrieve during file serving

### ISSUE THREAD

**Issue by simpleusr** [spring-cloud/spring-cloud-config#2101] opened 2022-06-06 16:15 UTC
Hi,

I am trying to utilize spring cloud config server for config file serving from a git backend.

Given correct parameters, org.springframework.cloud.config.server.resource.ResourceController serves the requested file successfully over http.

However, there seems to be a contention when handling concurrent requests. 
Parallelizing file requests in the client side does not help since there seems to be a contention in org.springframework.cloud.config.server.resource.ResourceController.retrieve method which is declared as synchronized.

The contention can be verified by java flight recorder 

![jfr](https://user-images.githubusercontent.com/5550814/172201258-eaf4d4c0-554c-4896-b56b-ef5a9b8fde56.png)

using the simple sample apps.

https://github.com/simpleusr/testapps

Is such a degree of mutual exclusion really required when serving files? Can this be improved?

Regards

**Comment by ryanjbaxter** [comment] 2022-06-06 23:50
Not entirely sure why, there might be some history there I am not aware of because its been syncronized for a while now.

**Comment by hpoettker** [comment] 2022-06-23 01:10
See also #2069.

**Comment by spencergibb** [comment] 2022-07-05 14:15
Duplicate of #2069

**Closed by spencergibb** 2022-07-05 14:15 UTC
Labels: for team discussion
