### ISSUE TITLE
Missing 'logging.file.name' or 'logging.file.path' proper

### ISSUE THREAD

**Issue by vidbin** [spring-cloud/spring-cloud-config#1592] opened 2020-04-05 17:16 UTC
hi,when i using spring cloud config(version is 2.2.2.Release) , i want to make the properties ‘logging.file.name’ sharing with defferent microservice. so i place "logging.file.name" into the file application.yml in spring cloud config project,  but not effective when i get endpoint of demo-service like "http://localhost:8080/actuator/logfile"（that url is belong to  demo-service）
this is my config central dir:
![image](https://user-images.githubusercontent.com/56708173/78504998-fcecb500-77a2-11ea-8386-c785d003f0a3.png)

my spring cloud config bootstrap.yml like this:
![image](https://user-images.githubusercontent.com/56708173/78505085-a6cc4180-77a3-11ea-8e3c-ba0e7c57e82c.png)

the application.yml that contain some properties that i want to share with many different microservice:
![image](https://user-images.githubusercontent.com/56708173/78505125-e3983880-77a3-11ea-9817-a71857414e51.png)

**Comment by ryanjbaxter** [comment] 2020-04-06 14:04
What does not effective mean?

**Comment by JoJo-Guo** [comment] 2020-04-06 14:35
> What does not effective mean?

sorry, my english is so poor. i want to make the property, logging.file.name that spring boot build-in ,shared between all microservices, so i place the property in resources with file names in application.yml. but when i visiting the actuator endpoint 'logfile' of config-client, i can't get log. in the backend console,  it show message like this : "Missing 'logging.file.name' or 'logging.file.path' properties".

**Comment by spencergibb** [comment] 2020-04-07 14:47
what does `/actuator/env` say?

**Comment by spring-issuemaster** [comment] 2020-04-14 14:50
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by JoJo-Guo** [comment] 2020-04-18 03:32
the `/actuator/env` show that the value of  `LOG_FILE` is `logs/demo-service/demo-service-9595.log` that is congurated in spring cloud config center  `application.yml`  file shared beteewen with many other microservices.

**Comment by spencergibb** [comment] 2020-04-18 03:39
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by JoJo-Guo** [comment] 2020-04-18 05:56
this is a minimal sample. you can visit ‘http://localhost:9595/actuator/logfile’ that will be no log file exsiting.
[config-central-sample.zip](https://github.com/spring-cloud/spring-cloud-config/files/4496119/config-central-sample.zip)

**Comment by spencergibb** [comment] 2021-03-30 17:54
Sorry for the delay. From config server
```
$ http :7070/demo-service/default                                                                                                                                                 
HTTP/1.1 200 
Connection: keep-alive
Content-Type: application/json
Date: Tue, 30 Mar 2021 17:48:58 GMT
Keep-Alive: timeout=60
Transfer-Encoding: chunked

{
    "label": null,
    "name": "demo-service",
    "profiles": [
        "default"
    ],
    "propertySources": [
        {
            "name": "classpath:/native-config/application.yml",
            "source": {
                "logging.file.name": "logs/${spring.application.name}/${spring.application.name}-${server.port}.log",
                "logging.level.root": "info",
                "management.endpoint.health.show-details": "always",
                "management.endpoints.web.exposure.include": "*"
            }
        }
    ],
    "state": null,
    "version": null
}
```
And from the microservice (using boot 2.3.9 and Hoxton.SR10)
```
 http :9595/actuator/env/logging.file.name                                                                                                                                       (10007)[13:52:39]
HTTP/1.1 200 
Connection: keep-alive
Content-Disposition: inline;filename=f.txt
Content-Type: application/vnd.spring-boot.actuator.v3+json
Date: Tue, 30 Mar 2021 17:52:41 GMT
Keep-Alive: timeout=60
Transfer-Encoding: chunked

{
    "activeProfiles": [],
    "property": {
        "source": "bootstrapProperties-classpath:/native-config/application.yml",
        "value": "logs/demo-service/demo-service-9595.log"
    },
    "propertySources": [
        {
            "name": "bootstrapProperties-classpath:/native-config/application.yml",
            "property": {
                "value": "logs/demo-service/demo-service-9595.log"
            }
        }
    ]
}
```
Looks like it is working.

**Comment by spring-cloud-issues** [comment] 2021-04-06 17:58
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-04-13 17:57
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-04-13 17:57 UTC
Labels: feedback-reminder, waiting for feedback
