### ISSUE TITLE
PropertyPathEndpoint ignores port when it compute serviceName 

### ISSUE THREAD

**Issue by RaphC** [spring-cloud/spring-cloud-config#436] opened 2016-06-29 17:03 UTC
I'm testing spring-cloud-conifg with spring-cloud-bus.

I'm using gitlab repo. So I set my webhook. 
My configserver instance received the hook and send an event in my amqp queue. The message is received by my config client instance but it does nothing. 

Here is the amqp message received by the config client instance :
```
2016-06-29 18:56:21.416 DEBUG [springCloudBus.anonymous.rY9eo0eZQ-6VOphA8MCSGA-1] BlockingQueueConsumer - Received message: (Body:'{"type":"RefreshRemoteApplicationEvent","timestamp":1467219381398,"originService":"configServer:tbd:8080","destinationService":"myapp:dev","id":"c56c0148-46af-4105-968d-d087748b0621"}'MessageProperties [headers={contentType=text/plain, originalContentType=application/json}, timestamp=null, messageId=null, userId=null, appId=null, clusterId=null, type=null, correlationId=null, replyTo=null, contentType=text/plain, contentEncoding=null, contentLength=0, deliveryMode=null, expiration=null, priority=0, redelivered=false, receivedExchange=springCloudBus, receivedRoutingKey=springCloudBus, deliveryTag=1, messageCount=0])
```
Am I missing something ?

**Comment by spencergibb** [comment] 2016-06-29 17:13
Any more information you could give would be helpful, versions, configuration, etc...

**Comment by RaphC** [comment] 2016-06-30 11:42
Here are the different information


my client configuration bootstrap.yml

```
spring:
  application:
    name: myapp
  rabbitmq:
    host: <rabbitmq_host>
    port: 5672
    username: <username>
    password: <password>
  cloud:
    config:
       uri: <configserver_uri> 
       failFast: true # echec demarrage si config server injoignable
       label: feature-piranas-support #tant qu'on est sur la branche. A virer après le merge sur develop
       retry:
        max-attempts: 3
  profiles:
    active: dev
```

my client pom.xml

```
       <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.5.RELEASE</version>
	</parent>


        <!-- spring boot dependencies -->
        <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jersey</artifactId>
        </dependency>
		<dependency>
		    <groupId>org.springframework.boot</groupId>
		    <artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		<dependency>
        	<groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jetty</artifactId>
        </dependency>

        <!-- spring cloud dependencies -->
        <dependency>
	        <groupId>org.springframework.cloud</groupId>
	        <artifactId>spring-cloud-starter-config</artifactId>
    	</dependency>
    	<dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-starter-bus-amqp</artifactId>
		    <version>1.1.0.RELEASE</version>
		</dependency>
```

my config server bootstrap.yml

```
spring:
  application:
    name: piranas
  main:
    banner-mode: "off"
  rabbitmq:
    host: <rabbit_host>
    port: 5672
    username: <rabbit_username>
    password: <rabbit_password>

...
---
spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      enabled: false # n'est pas un client lui-même
      server:
        monitor:
          gitlab:
            enabled: true 
          github:
            enabled: false
          bitbucket:
            enabled: false
        encrypt:
          enabled: false # Les donnees securisees ne sont pas dechiffrer par le serveur lui-même
        git:
          uri: <my_git_uri>
          # repertoire dans lequel sont clonés les repos
          basedir: ${HOME}/git_repo
          # timeout en secondes
          timeout: 10
          # default search path 
          # Pb pour les repo qui heberge plusieurs applications
          searchPaths: 
           - '{application}-conf/{profile}/conf'
           - '{application}-conf/{profile}/'

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
    com.bouygtel: DEBUG
```

my configserver pom

```
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.3.5.RELEASE</version>
	</parent>

	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
			<version>1.1.1.RELEASE</version>
		</dependency>
		<dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-config-monitor</artifactId>
		    <version>1.1.1.RELEASE</version>
		</dependency>
		<dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-starter-bus-amqp</artifactId>
		    <version>1.1.0.RELEASE</version>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
		</dependency>
	</dependencies>
```

I can see in my config server log the webhook /monitor and the sending a amqp message. I can see the message consumed  by my client. What is the classe which trigger the rebinding after received amqp message ?

Thanks

**Comment by RaphC** [comment] 2016-06-30 15:17
I guess I'm not understand at well the flow.

I thought when my got repo execute the webhook /monitor on my config server instance , this one emit an event each application receives. If one instance is concerned by the change detection it reload its application's configuration.

I made a second test by disabling /monitor webhook and calling on one of the instance the /bus/refresh?destination="myapp:**". So far so good, the correspond instances receives the event and reload their configuration.

Can you details the flow. What is the benefit of webhook if I have to call /resresh endpoint ?

**Comment by RaphC** [comment] 2016-06-30 15:27
Sorry,

I found the problem : I simulated webhook with a modified attribute like <application_name>-<profile>.yml. So my client received  the event but ignored it.

curl -H "Content-type: application/json" -H "X-Gitlab-Event: Push Hook" -d '{"commits": [{"id": "b6568db1bc1dcd7f8b4d5a946b0b91","message": "Update application configuration.","timestamp": "2011-12-12T14:27:31+02:00","author": {"name": "Me","email": "me@mymail.fr"},"added": [],"modified": ["conf/<application_name>-<profile>.yml"],"removed": []}]}' -X POST http://<config_server_uri>/monitor -vvv


If I changed my request body by a modified attribute like <application_name>.yml it works.

curl -H "Content-type: application/json" -H "X-Gitlab-Event: Push Hook" -d '{"commits": [{"id": "b6568db1bc1dcd7f8b4d5a946b0b91","message": "Update application configuration.","timestamp": "2011-12-12T14:27:31+02:00","author": {"name": "Me","email": "me@mymail.fr"},"added": [],"modified": ["conf/<application_name>.yml"],"removed": []}]}' -X POST http://<config_server_uri>/monitor -vvv


Thanks

**Comment by RaphC** [comment] 2016-07-01 10:38
Finally I guess there's an issue about the computation of serviceName in the method guessServiceName of the PropertyPathEndpoint.

If I have a file named <my_application>-<my_profile>.yml, the component build 2 destinationServices :

* "<my_application>:<my_profile>"
* "<my_application>-<my_profile>:**"

Unfortunately, the default appId computation as mentionned spring-cloud-bus documentation combines <my_application>:<my_profile>:<my_port>

So I think the component should append "<my_application>:<my_profile>" with ** like that "<my_application>:<my_profile>:**" to correctly addressed the targeted application.

**Comment by spencergibb** [comment] 2016-07-01 22:43
@RaphC PR?

**Comment by dsyer** [comment] 2016-08-16 14:49
The problem is actually better fixed in the bus IMO (see link above).

**Closed by dsyer** 2016-08-16 14:49 UTC
Labels: bug

**Comment by RaphC** [comment] 2016-08-16 18:00
Hy dsyer,

Thank you.
