### ISSUE TITLE
may publish a config file about spring-cloud-config's all properties  

### ISSUE THREAD

**Issue by 995270418L** [spring-cloud/spring-cloud-config#822] opened 2017-10-14 12:05 UTC

**Comment by spencergibb** [comment] 2017-10-14 13:57
Please provide a detailed description of the problem and how to reproduce it.

**Comment by spencergibb** [comment] 2018-01-18 01:33
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-01-18 01:33 UTC
Labels: waiting for feedback
