### ISSUE TITLE
Config server returns extra backslash when decrypting cipher

### ISSUE THREAD

**Issue by marnee01** [spring-cloud/spring-cloud-config#1243] opened 2019-02-04 17:54 UTC
We have a password that contains a backslash and a double quote. When it is decrypted directly using the .../decrypt URL, the password is decrypted back to its original form. However, when we retrieve the properties, the password is decrypted with extra backslashes added.

To reproduce:

1. Call the .../encrypt endpoint with Content Type "text/plain" and with this password: Weird\[chars"[]^hello!@#$%^&*()
2. Call the .../decrypt endpoint with the value returned from #1. The password is decrypted correctly.
3.  Copy the returned value from #1 and add to a property in your client's repo with the {cipher} prefix.
4. Call the .../{appname}/{profiles}/{label} endpoint for your client.
Expected: The password is returned as: Weird\[chars"[]^hello!@#$%^&*()
Observed: The password is returned as: Weird\\[chars\"[]^hello!@#$%^&*()
It has an extra backslash before the backslash and before the double quote.

**Comment by marnee01** [comment] 2019-02-04 17:56
Clarification: For step #2, I used Content-type "text/plain".

**Comment by ryanjbaxter** [comment] 2019-02-13 22:05
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by marnee01** [comment] 2019-02-18 20:04
We have resolved it as a side-effect of another change in which we no longer need this password. Therefore, this is not a high priority for us at the moment. I will create a sample when time permits.

FYI, we are using the Edgware SR4 build.

**Comment by spring-issuemaster** [comment] 2019-02-25 20:07
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-03-04 20:07
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-03-04 20:07 UTC
Labels: feedback-reminder, waiting for feedback
