### ISSUE TITLE
Spring boot 2.4.X with Cloud Config Legacy Loading - actuator/refresh is Not working

### ISSUE THREAD

**Issue by shivudu** [spring-cloud/spring-cloud-config#1803] opened 2021-02-19 08:55 UTC
We have upgraded from sprig version 2.1.x to 2.4.X and cloud - Greenwich to 2020.0.X.
Included spring boot spring-cloud-starter-bootstrap to load properties.. its working fine on app initial startup.
However actuator/refresh isn't working...
**Upon debugging further found out that - Its not taking name from spring.application.name while connecting to cloud config server - application name defaulted to 'application'**

Reference - 
https://github.com/spring-cloud/spring-cloud-config/blob/63e0a99f898fe28bf09bb1e1d5f88be19dd01d0f/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java#L214

**Comment by ryanjbaxter** [comment] 2021-02-19 15:34
It is only not working when you make a POST to `/actuator/refresh`?

**Comment by shivudu** [comment] 2021-02-19 16:06
Yes, on startup it’s loading properties, but when I do POST actuator/refresh it’s not working.

**Comment by ryanjbaxter** [comment] 2021-02-19 21:07
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by dyroberts** [comment] 2021-02-25 17:58
@ryanjbaxter I'm experiencing this with spring-cloud-services acceptance tests as well.

**Comment by dyroberts** [comment] 2021-02-25 20:42
Here's the apps (client/server) I used to reproduce locally: https://github.com/dyroberts/1803-spring-cloud-config
Using the default host and port (localhost:8888) works. Anything else seems not to work.

**Comment by spencergibb** [comment] 2021-02-26 15:14
ping @dyroberts I'm unable to reproduce using your sample. What exact steps do I need to do to replicate?

**Comment by shivudu** [comment] 2021-03-01 12:22
Hi @spencergibb , just have cloud config-client with version 2020.0.1 and add dependency spring-cloud-starter-bootstrap, use legecy loading using property - spring.cloud.config.uri to pull props from server. do a post on actuator/refresh.

Then if you can debug this method upon refresh, you can notice name (spring.application.name) defaulted to 'application'.
https://github.com/spring-cloud/spring-cloud-config/blob/63e0a99f898fe28bf09bb1e1d5f88be19dd01d0f/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServicePropertySourceLocator.java#L214

**Comment by shivudu** [comment] 2021-03-01 12:53
@ryanjbaxter if you are using spring.cloud.config.uri with cloud version 2020.0.1 you should have dependency / use properties to get it working on initial startup of application. 
check out - https://spring.io/blog/2020/12/22/spring-cloud-2020-0-0-aka-ilford-is-available
Also note - spring.cloud.config.uri should be in env /bootstrap.properties to get it working

**Comment by dyroberts** [comment] 2021-03-01 15:05
> Here's the apps (client/server) I used to reproduce locally: https://github.com/dyroberts/1803-spring-cloud-config
> Using the default host and port (localhost:8888) works. Anything else seems not to work.

This is not reproducing the issue after all. Please disregard. I'll potentially file a separate issue if needed.

**Comment by spencergibb** [comment] 2021-03-15 15:20
@shivudu I'm unable to reproduce this problem. I'm going to need a sample as requested https://github.com/spring-cloud/spring-cloud-config/issues/1803#issuecomment-782352216

**Comment by spring-cloud-issues** [comment] 2021-03-22 15:23
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-03-29 15:23
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-03-29 15:23 UTC
Labels: feedback-reminder, waiting for feedback
