### ISSUE TITLE
Allow detecting application using full path on GIT

### ISSUE THREAD

**Issue by mrodal** [spring-cloud/spring-cloud-config#2433] opened 2024-06-25 19:59 UTC
**Is your feature request related to a problem? Please describe.**
We need to serve properties and other raw files to applications and want to group them by directory, 
Eg:
```
- application1
  - properties.yaml
  - cert.crt
  - template.pdf
- application2
  - properties.yaml
```

The issue we are having is that when the repository is updated, application1 is not notified of the change because only the file name is used to determine the destination application.

**Describe the solution you'd like**
We would need something to allow us to use the path to determine the target application to be notified

**Describe alternatives you've considered**
Maybe allow customizing the application extracted based on the repo change

**Comment by ryanjbaxter** [comment] 2024-06-25 20:25
So only application2 is being notified?

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by mrodal** [comment] 2024-06-25 20:34
Thanks for the quick response
None of the applications is notified. For example if we change `application1/template.pdf`, the event that config-monitor propagates is for application `template`, and not for `application1`.

Looking at the code we can see that the method `guessServiceName` in [PropertyPathEndpoint](https://github.com/spring-cloud/spring-cloud-config/blob/main/spring-cloud-config-monitor/src/main/java/org/springframework/cloud/config/monitor/PropertyPathEndpoint.java#L105) extracts the filename and uses it for the event.

The documentation mentions [here](https://docs.spring.io/spring-cloud-config/reference/server/environment-repository/file-system-backend.html) that 

> The search locations can contain placeholders for {application}, {profile}, and {label}. In this way, you can segregate the directories in the path and choose a strategy that makes sense for you (such as subdirectory per application or subdirectory per profile).

But we couldnt make it work that way

**Comment by ryanjbaxter** [comment] 2024-07-01 13:07
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by mrodal** [comment] 2024-07-01 18:37
Here's the sample: [spring cloud config.zip](https://github.com/user-attachments/files/16057678/spring.cloud.config.zip)

This is the config structure in the sample:

![image](https://github.com/spring-cloud/spring-cloud-config/assets/20667544/acadbf3e-e32f-4727-8eff-154f8d6e7c4a)


Here are the kafka events produced when some files change:

You can see that application1 is not in `destinationService` for the changes to `application1/properties-dev.yaml` nor `application1/cert.crt`, only for the file with the application name in the file name. And as mentioned before, we would like `application1` to be notified for any change in the files inside `application1/*`



### application1/application1-properties-dev.yaml
![image](https://github.com/spring-cloud/spring-cloud-config/assets/20667544/10387ee3-de19-4db2-b841-1d0d7beab045)

### application1/properties-dev.yaml
![image](https://github.com/spring-cloud/spring-cloud-config/assets/20667544/cbf03410-4a96-4211-bccd-764d0340a2f6)

### application1/cert.crt
![image](https://github.com/spring-cloud/spring-cloud-config/assets/20667544/23982924-0c26-4ee6-a1fa-2e67b7f71e23)

**Comment by spring-cloud-issues** [comment] 2024-08-30 16:05
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2024-09-06 16:05
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2024-09-06 16:05 UTC
Labels: feedback-reminder
