### ISSUE TITLE
Spring cloud config server behaving unexpectedly with multiple labels.

### ISSUE THREAD

**Issue by Swatikp** [spring-cloud/spring-cloud-config#1238] opened 2019-01-28 14:58 UTC
Bug report

I am using spring cloud config server with spring boot and vert.x clients. I have at around 30 clients which use the same config server with same git repo. The vert.x client keeps on polling data from config server after every 5 seconds.

The problem I am facing is, around 20 of my applications are trying to fetch property from config server with following label:
`spring.cloud.config.label=DEV`  (where DEV is one branch in github repo)

and one application (lets say the application name is appX) is trying to fetch properties from following label: 

`spring.cloud.config.label=feature`  (where feature is one branch in github repo)

But the problem is that whenever there are any changes in branch **feature**, they are not reflected by the spring cloud config server, because maybe config server is not able to checkout the changes completely for feature branch and request for **DEV** branch keeps on coming continuously. And it gives back old files for **feature** branch .

How am I supposed to handle multiple labels in config server by enforcing them to fetch latest files.

**Comment by spencergibb** [comment] 2019-01-28 17:12
can you say why you are polling so often? Config server (especially with git) was not made to be polled to so often.

**Comment by Swatikp** [comment] 2019-01-29 05:10
Hi @spencergibb , it is the default refresh rate of a vert.x application that is the scan period after which vert.x application tries to fetch the configuration.  But this is not the problem, even if I increase the refresh rate, I have multiple clients which are using Label - **DEV**, and one client is using label -**feature**, even though I call /refresh endpoint from my clients, all clients using  **DEV**  label are able to update the properties, but the properties of client which is using **feature** are taking a long long time to refresh (the time varies everytime), So we cannot guarantee that the property we are using will be the latest even after hitting refresh API.

**Comment by spencergibb** [comment] 2019-02-11 16:37
I can't say why. This should work fine.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-02-18 16:37
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-02-25 16:37
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-02-25 16:37 UTC
Labels: feedback-reminder, waiting for feedback
