### ISSUE TITLE
After upgrade spring config server , aws s3 config server is not working 

### ISSUE THREAD

**Issue by jaganm2018** [spring-cloud/spring-cloud-config#1903] opened 2021-06-09 12:38 UTC
Dependencies and version:
——————————————-
Spring boot : 2.5.0
Spring cloud function : 3.1.3
Spring cloud config server: 3.0.4
Aws-Java-ask-s3 : 1.11.1019
Spring cloud starter bootstrap: 3.0.3 

bootstrap.yml
————————-
spring:
  application:
    name: Demo
  profiles:
    active: dev
  cloud: 
    config: 
       profile: awss3
      server:
        awss3:
           region: us-east-1
           bucket: sample-bucket

Aws s3:
—————
 Bucket : sample-bucket
 App folder under bucket: Demo
 Properties file under app folder : application-dev.properties 

Deployed in to lambda function and specified the spring_cloud_function_definition: fetch
spring_profiles_active: dev

Code:
————-
Added @EnableConfigServer in DemoApplication.Java (spring boot application)

Scenario-1: 
Did lambda test with above configuration : reading from the application.properties not from the application-dev.properties 
Seems it s not connected to aws S3. Even I didn’t see any bootstrap logs also.

scenario-2: removed spring_profiles_active: dev in the lambda environment 
Even it’s not working

scenario -3: keep bootstrap.yml properties into application.yml and ran the lambda test
Same situation as in scenario-1 

I tried lot of ways still not working .. please help me on this.

Note: looking for @refrsh scope also

**Comment by ryanjbaxter** [comment] 2021-06-09 13:02
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by jaganm2018** [comment] 2021-06-10 09:40
Sure I will do it. Let me prepare and share to you.

**Comment by jaganm2018** [comment] 2021-06-10 11:32
Hi Ryanjbaxter,
Please see git repo URl: https://github.com/jaganm2018/spring-cloud-function-aws

Please see below points:
1) This is spring cloud function with config-server (pointed to AWS S3 Bucket) and deployed into AWS lambda function.
2)  Below specified are the lambda env variables 
      spring_cloud_function_definition: fetch
     spring_profiles_active: dev
3) My AWS S3 Bucket and folder structure.
    sample-config (bucket name: specified in the bootstrap.yml)
            |
            |___ DemoApp (Application Folder Name: specified in the appication.properties)
                        |
                        |___ application-dev.properties

Issue 1: 
 Ran the application : it's always retrieve local application properties value instead of retrieve from config-server
 O/P: local
 expected value: dev

Issue-2: How to specified the search-patterns like {application}-{profile}.properties or application -> profile -> application.properties 

Issue-3: @RefreshScope will work awss3 bucket.

Appreciate for your help and thanks in advance. Waiting for your response.

**Comment by jaganm2018** [comment] 2021-06-11 03:28
why are you starting a Config Server in a function? I’m implementing for aws lambda function so I chooses spring function along with spring boot. Vault integration is working but config-server I’m facing issue. 

Another one for ec2 deploy also. 

Earlier we used the spring boot 2.3.8 release version and pointed to git repo. Now I’m moving latest and aws-s3. 

Thanks for replying & let me check and get back to you.

**Comment by jaganm2018** [comment] 2021-06-11 08:35
Hi,
Updated with spring boot 2.4.3 version and as per your suggestion. https://github.com/jaganm2018/spring-cloud-function-aws

but in your comment , I didn’t understand about spring cloud BOM? What’s that ?

**Comment by ryanjbaxter** [comment] 2021-06-11 15:58
See the maven and gradle examples here 
https://spring.io/projects/spring-cloud#overview

**Comment by jaganm2018** [comment] 2021-06-11 16:32
Already gone through those document and but no useful. Is it ok can you please involve @spencergibb in this conversation.. because I saw same error in another issue : 1635. But they are using 2.3.x spring boot. He helped to them last time.. might be he can us to fix this issue.

**Comment by ryanjbaxter** [comment] 2021-06-11 18:15
>Issue 1:
Ran the application : it's always retrieve local application properties value instead of retrieve from config-server
O/P: local
expected value: dev

This is why I am confused by your sample.  Its just a config server, so its not fetching config from itself.  Where is the config client application?

**Comment by jaganm2018** [comment] 2021-06-11 18:37
Config location is in aws-s3 bucket. 
1. My AWS S3 Bucket and folder structure.
sample-config (bucket name: specified in the bootstrap.yml)
|
|___ DemoApp (Application Folder Name: specified in the appication.properties)
|
|___ application-dev.properties

**Comment by jaganm2018** [comment] 2021-06-14 12:36
Any updates?

**Comment by ryanjbaxter** [comment] 2021-06-14 14:01
Your sample does not compile

**Comment by jaganm2018** [comment] 2021-06-14 14:53
Can you please try now? Seems import has issue with caps letter. Fixed. Thanks for relying.

**Comment by ryanjbaxter** [comment] 2021-06-14 15:29
Your configuration is not correct as you need to use a composite when spring.cloud.config.server.bootstrap=true
You can try this
```
spring:
  profiles:
    active: dev,composite
  cloud:
    config:
      server:
        composite:
        - type: aws
          region: us-east-1
          bucket: sample-config
        bootstrap: true
``

**Comment by jaganm2018** [comment] 2021-06-14 16:32
Thanks for checking but as per the new upgrade, spring.cloud.config.server.composite property is not available. It’s saying unknown property.

**Comment by spencergibb** [comment] 2021-06-14 16:33
What an ide says and what actually works are two different things

**Comment by jaganm2018** [comment] 2021-06-14 17:01
IDE saying , “Unknown property’spring.cloud.config.server.composite’. 

If I deploy my repository code, it’s not showing any error and not reading from aws-s3 bucket.

**Comment by ryanjbaxter** [comment] 2021-06-14 17:29
Did you deploy with the configuration I suggested?

**Comment by jaganm2018** [comment] 2021-06-14 17:46
Not yet.. let me try now .. give me few mins please

**Comment by jaganm2018** [comment] 2021-06-14 18:01
I ran with what you provided one.. after I deployed in to aws , got error as below.

{
 “ErrorMessage”: “error creating bean with name ‘defaultEnvironmentRepoaitory’ defined in the class path resource [org/springframework/cloud/config/server/config/DefaultRepositoryConfiguration.class]: Invocation of unit method failed; nested exception is Java.Lang.IllegalStateException: you need to configure  a uri for the git repost.”,
“ErrorType”: “org.springframework.beans.factory.BeanCreationExcep uni”
}

**Comment by jaganm2018** [comment] 2021-06-14 19:07
Please let me know if you need any more information. Actually 2.4.x spring boot version and spring cloud 2020.0.2. You can see my sample application in above comment section. 

Thanks in advance

**Comment by spencergibb** [comment] 2021-06-15 00:45
@jaganm2018 please update your repo with the updated configuration you tried.

**Comment by jaganm2018** [comment] 2021-06-15 03:55
@spencergibb updates with new configuration what @ryanjbaxter provided. Here in IDE , it’s showing  “Unknown property’spring.cloud.config.server.composite’”.


Please see below updated git repo
https://github.com/jaganm2018/spring-cloud-function-aws

**Comment by jaganm2018** [comment] 2021-06-15 16:49
Any updates?

**Comment by spencergibb** [comment] 2021-06-15 17:08
After removing spring cloud function, the thin launcher, and the  maven shade plugin and moving DemoApplication out of the default package and renaming Java to java (in other words, making a minimal project), I can not recreate the error

**Comment by jaganm2018** [comment] 2021-06-15 17:27
Can you please suggest me one thing ..
Do you have any sample on config-server with aws s3 with latest version? 

why it’s showing unknown property of spring.cloud.config.server.composite . Is this property deprecated or still available in latest version?

mean while let me update it that git repo.

**Comment by spencergibb** [comment] 2021-06-15 17:32
The property not being recognized by the ide has ZERO bearing on it actually working which I have verified thru the debugger. See https://github.com/spring-cloud/spring-cloud-config/issues/1909 to add the metadata. This project worked for me https://github.com/jaganm2018/spring-cloud-function-aws/pull/1

**Comment by jaganm2018** [comment] 2021-06-15 18:02
Is it working? Did you tested in aws -s3 side? 
Please let me know. If yes then I will test in aws side. Thanks.

**Comment by jaganm2018** [comment] 2021-06-15 22:46
Please let me know the current solution/fix for this?

**Comment by spencergibb** [comment] 2021-06-15 22:53
I have nothing to add besides my pr

**Comment by jaganm2018** [comment] 2021-06-16 19:18
Let me update the git repo with spring boot configuration and will let you know. Thanks.

**Comment by jaganm2018** [comment] 2021-06-20 12:36
Hi,
Thanks to all. It’s working ec2 but not in lambda.. seems some thing role access issue in aws. Let’s check it. 

Before closing this .. I have 2 issues ..
1. I’m running locally , I’m getting git uri configuration even I disabled the spring.cloud.config.enabled is false also in bootstrap.yml.  Even I tried spring.cloud.import .. seems some thing I’m missing.
2. Present its looking application-{profile}.yml/properties/Json. But I’m want to provide different search paths. 

Can you please suggest me where I did mistake.

Once again thanks for helping.

**Comment by jaganm2018** [comment] 2021-06-21 19:30
Any suggestions?

**Comment by spencergibb** [comment] 2021-06-22 01:28
My pr worked locally. What is different?

**Comment by jaganm2018** [comment] 2021-06-22 09:26
Hi,
Thanks to all. It’s working ec2 but not in lambda.. seems some thing role access issue in aws. Let’s check it.

Before closing this .. I have 2 issues ..

I’m running locally , I’m getting git uri configuration even I disabled the spring.cloud.config.enabled is false also in bootstrap.yml. Even I tried spring.cloud.import .. seems some thing I’m missing.
Present its looking application-{profile}.yml/properties/Json. But I’m want to provide different search paths.
Can you please suggest me where I did mistake.

Once again thanks for helping.

**Comment by jaganm2018** [comment] 2021-06-24 15:08
Any updates on above my question?

**Comment by spencergibb** [comment] 2021-06-24 16:02
are the two items listed new? I was able to get the app running locally (see my PR). Have you changed anything? If so push it to the example and describe how to recreate it.

**Comment by jaganm2018** [comment] 2021-06-24 18:36
I ran locally with composite and local properties then it trying to connect to aws s3 config server. I want to disabled the config-server by using spring.cloud.config.enabled=False. It’s not working. What I can do?

**Comment by ryanjbaxter** [comment] 2021-06-30 21:09
How are you setting `spring.cloud.config.enabled=false`?

**Comment by jaganm2018** [comment] 2021-07-02 13:48
Setting this in boot strap yml file.

**Comment by ryanjbaxter** [comment] 2021-07-06 14:41
Can you try setting it in an environment variable?

**Comment by jaganm2018** [comment] 2021-07-07 20:25
It’s not working. I tried in the profile based application properties, it’s working fine.
Another question is .. how to disabled spring.cloud.config.server.vault property. I didn’t see enabled: true/false option under that above property. Seems it’s trying to connect to vault server. How I can disabled.

**Comment by spencergibb** [comment] 2021-07-07 20:33
Please keep this to a single issue with s3. Is your example updated with the things you have tried? This conversation is so long and disjointed that it's hard to understand. Let us know when your project is able to replicate the latest problem.

**Comment by jaganm2018** [comment] 2021-07-09 04:47
Sure. Let me close this issue and create new one with sample. Thanks a lot.

**Comment by spencergibb** [comment] 2021-07-09 04:50
No just update the sample here

**Comment by spring-cloud-issues** [comment] 2021-12-10 20:35
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-12-17 20:35
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-12-17 20:35 UTC
Labels: waiting for feedback, feedback-reminder
