### ISSUE TITLE
MemoryLeak related to the HealthCheck

### ISSUE THREAD

**Issue by xjodoin** [spring-cloud/spring-cloud-config#668] opened 2017-03-14 15:11 UTC
Each time the health check is build it create a new NativeEnvironmentRepository that will create URLResource and each time you load jar resource it will register the file in java.io.DeleteOnExitHook. So after a time you bust the memory.

Config server memory dump: https://s3.amazonaws.com/xjodoin-public/dump.hprof.gz

**Comment by spencergibb** [comment] 2017-03-24 20:56
Any more details you can give? What version are you using? Configuration? Platform?

**Comment by abhsc** [comment] 2017-05-23 13:11
I am also having this issue. I am running spring boot 1.5.3.RELEASE 

    endpoints:
      enabled: false
      health:
        enabled: true
        sensitive: false
    management:
      security:
        enabled: false
      port: 8588 
   
The config server is running within a docker container and memory leak/ get killed, restart and repeat. The endpoint is being called as part of the docker healthcheck:

    HEALTHCHECK &{["CMD-SHELL" "curl -s -o /dev/null -w \"%{http_code}\" http://localhost:8588/health | grep 200"] "15s" "3s" '\b'}

**Comment by xjodoin** [comment] 2017-05-23 14:14
docker openjdk:8 spring boot 1.4.1.RELEASE spring cloud Camden.RELEASE

**Comment by ryanjbaxter** [comment] 2017-05-24 14:19
Can you try with `Dalston.RELEASE`?

**Comment by abhsc** [comment] 2017-05-24 15:40
@xjodoin Could you also supply what JVM arguments you pass into the java command within the docker image? Thanks.

**Comment by xjodoin** [comment] 2017-05-24 16:39
-Xmx1920m

**Comment by Rambrant** [comment] 2017-07-19 11:42
We have the same problem in version 1.5.4
We run Docker 17.06-ce

**Comment by yotamoron** [comment] 2017-08-15 09:24
Any news on this issue?

**Comment by ryanjbaxter** [comment] 2017-08-15 11:34
@yotamoron we are waiting for someone to confirm they can reproduce it using the latest `Dalston` release.

**Comment by john-mcpeek** [comment] 2017-08-26 16:34
I am seeing a lot of startup and shutdown. This happens for ever call.

springCloudVersion = 'Dalston.RELEASE'

2017-08-26 12:32:00.874  INFO 454860 --- [           main] i.v.config.ConfigServerApplication       : Started ConfigServerApplication in 7.041 seconds (JVM running for 7.711)
2017-08-26 12:32:08.182  INFO 454860 --- [nio-8888-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2017-08-26 12:32:10.203  INFO 454860 --- [nio-8888-exec-1] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@5173ef0f: startup date [Sat Aug 26 12:32:10 EDT 2017]; root of context hierarchy
2017-08-26 12:32:10.224  INFO 454860 --- [nio-8888-exec-1] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-26 12:32:10.251  INFO 454860 --- [nio-8888-exec-1] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@5173ef0f: startup date [Sat Aug 26 12:32:10 EDT 2017]; root of context hierarchy
2017-08-26 12:32:11.425  INFO 454860 --- [nio-8888-exec-2] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@640777b2: startup date [Sat Aug 26 12:32:11 EDT 2017]; root of context hierarchy
2017-08-26 12:32:11.431  INFO 454860 --- [nio-8888-exec-2] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-26 12:32:11.438  INFO 454860 --- [nio-8888-exec-2] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@640777b2: startup date [Sat Aug 26 12:32:11 EDT 2017]; root of context hierarchy
2017-08-26 12:32:12.408  INFO 454860 --- [nio-8888-exec-3] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@3251808c: startup date [Sat Aug 26 12:32:12 EDT 2017]; root of context hierarchy
2017-08-26 12:32:12.413  INFO 454860 --- [nio-8888-exec-3] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-26 12:32:12.420  INFO 454860 --- [nio-8888-exec-3] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@3251808c: startup date [Sat Aug 26 12:32:12 EDT 2017]; root of context hierarchy
2017-08-26 12:32:13.235  INFO 454860 --- [nio-8888-exec-4] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@24ff28c1: startup date [Sat Aug 26 12:32:13 EDT 2017]; root of context hierarchy
2017-08-26 12:32:13.241  INFO 454860 --- [nio-8888-exec-4] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-26 12:32:13.248  INFO 454860 --- [nio-8888-exec-4] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@24ff28c1: startup date [Sat Aug 26 12:32:13 EDT 2017]; root of context hierarchy
2017-08-26 12:32:14.023  INFO 454860 --- [nio-8888-exec-6] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@597801af: startup date [Sat Aug 26 12:32:14 EDT 2017]; root of context hierarchy
2017-08-26 12:32:14.030  INFO 454860 --- [nio-8888-exec-6] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-26 12:32:14.036  INFO 454860 --- [nio-8888-exec-6] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@597801af: startup date [Sat Aug 26 12:32:14 EDT 2017]; root of context hierarchy
2017-08-26 12:32:14.868  INFO 454860 --- [nio-8888-exec-5] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7d1ba8ae: startup date [Sat Aug 26 12:32:14 EDT 2017]; root of context hierarchy
2017-08-26 12:32:14.873  INFO 454860 --- [nio-8888-exec-5] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-26 12:32:14.879  INFO 454860 --- [nio-8888-exec-5] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@7d1ba8ae: startup date [Sat Aug 26 12:32:14 EDT 2017]; root of context hierarchy
2017-08-26 12:32:15.788  INFO 454860 --- [nio-8888-exec-9] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@79617115: startup date [Sat Aug 26 12:32:15 EDT 2017]; root of context hierarchy
2017-08-26 12:32:15.793  INFO 454860 --- [nio-8888-exec-9] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-26 12:32:15.797  INFO 454860 --- [nio-8888-exec-9] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@79617115: startup date [Sat Aug 26 12:32:15 EDT 2017]; root of context hierarchy
2017-08-26 12:32:16.669  INFO 454860 --- [nio-8888-exec-8] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@6e58fb57: startup date [Sat Aug 26 12:32:16 EDT 2017]; root of context hierarchy
2017-08-26 12:32:16.674  INFO 454860 --- [nio-8888-exec-8] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-26 12:32:16.678  INFO 454860 --- [nio-8888-exec-8] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@6e58fb57: startup date [Sat Aug 26 12:32:16 EDT 2017]; root of context hierarchy
2017-08-26 12:32:17.478  INFO 454860 --- [nio-8888-exec-7] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@2a9f5f8d: startup date [Sat Aug 26 12:32:17 EDT 2017]; root of context hierarchy
2017-08-26 12:32:17.484  INFO 454860 --- [nio-8888-exec-7] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-26 12:32:17.489  INFO 454860 --- [nio-8888-exec-7] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@2a9f5f8d: startup date [Sat Aug 26 12:32:17 EDT 2017]; root of context hierarchy
2017-08-26 12:32:18.398  INFO 454860 --- [io-8888-exec-10] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@21cccbd0: startup date [Sat Aug 26 12:32:18 EDT 2017]; root of context hierarchy
2017-08-26 12:32:18.403  INFO 454860 --- [io-8888-exec-10] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-26 12:32:18.410  INFO 454860 --- [io-8888-exec-10] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@21cccbd0: startup date [Sat Aug 26 12:32:18 EDT 2017]; root of context hierarchy
2017-08-26 12:32:19.328  INFO 454860 --- [nio-8888-exec-1] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@d2bbbe3: startup date [Sat Aug 26 12:32:19 EDT 2017]; root of context hierarchy
2017-08-26 12:32:19.332  INFO 454860 --- [nio-8888-exec-1] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-26 12:32:19.336  INFO 454860 --- [nio-8888-exec-1] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@d2bbbe3: startup date [Sat Aug 26 12:32:19 EDT 2017]; root of context hierarchy
2017-08-26 12:32:20.205  INFO 454860 --- [nio-8888-exec-2] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@7d72a297: startup date [Sat Aug 26 12:32:20 EDT 2017]; root of context hierarchy
2017-08-26 12:32:20.210  INFO 454860 --- [nio-8888-exec-2] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-26 12:32:20.214  INFO 454860 --- [nio-8888-exec-2] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@7d72a297: startup date [Sat Aug 26 12:32:20 EDT 2017]; root of context hierarchy
2017-08-26 12:32:21.085  INFO 454860 --- [nio-8888-exec-3] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@45c046ed: startup date [Sat Aug 26 12:32:21 EDT 2017]; root of context hierarchy
2017-08-26 12:32:21.090  INFO 454860 --- [nio-8888-exec-3] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-08-26 12:32:21.097  INFO 454860 --- [nio-8888-exec-3] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@45c046ed: startup date [Sat Aug 26 12:32:21 EDT 2017]; root of context hierarchy

**Comment by loicoudot** [comment] 2017-11-29 16:58
I can confirm the same problem on Dalston.SR4, and it's not only the `/health` but on every `spring-cloud-config` urls.

I've dig a bit and found the root problems:
- leaks occurs when `spring-cloud-config-server` is launched with java : `java -jar my-spring-cloud-config-server.war`
- there is no leak if the same war is launched with maven : `mvn spring-boot:run`

The leaks come from ` NativeEnvironmentRepository.findOne()` which build a `new SpringApplicationBuilder()` which in turn need to access some files within jar files. This `findOne()` method is called on every request including `/health`.

- When launching a war with mvn spring-boot:run, all the jar dependencies of the war is added to the class path and the URL to access a file is of the form: `jar:file:/.m2/my.jar!/META-INF/spring.factories`
- When launching from java, all the jar dependencies are inside the war and the URL are of the form: `jar:war:file:/mywar.war*/WEB-INF/lib/my.jar!/META-INF/spring.factories]`

So, for the latter case, with `war:` protocol, Java need to decompress `my.jar` to temp directory to access it's content. The method `sun.net.www.protocol.jar.URLJarFile.retrieve()` is responsible for this operation, and we fall into the memory leak of the JVM with the `deleteOnExit()` : https://bugs.openjdk.java.net/browse/JDK-4872014.

Until `spring-cloud-config` use a new `SpringApplicationBuilder` for each request, there will be some memory leaks.

FYI the call stack with the `war:` protocols:

```
add:58, DeleteOnExitHook (java.io) <= Memory Leak
deleteOnExit:1079, File (java.io)
run:222, URLJarFile$1 (sun.net.www.protocol.jar)
run:216, URLJarFile$1 (sun.net.www.protocol.jar)
doPrivileged:-1, AccessController (java.security)
retrieve:215, URLJarFile (sun.net.www.protocol.jar)
getJarFile:71, URLJarFile (sun.net.www.protocol.jar) <= differ with `file:` protocols
get:109, JarFileFactory (sun.net.www.protocol.jar)
connect:122, JarURLConnection (sun.net.www.protocol.jar)
getInputStream:150, JarURLConnection (sun.net.www.protocol.jar)
getInputStream:169, UrlResource (org.springframework.core.io)
fillProperties:132, PropertiesLoaderUtils (org.springframework.core.io.support)
loadProperties:121, PropertiesLoaderUtils (org.springframework.core.io.support)
loadFactoryNames:117, SpringFactoriesLoader (org.springframework.core.io.support)
getSpringFactoriesInstances:391, SpringApplication (org.springframework.boot)
getSpringFactoriesInstances:383, SpringApplication (org.springframework.boot)
initialize:249, SpringApplication (org.springframework.boot)
<init>:225, SpringApplication (org.springframework.boot)
createSpringApplication:99, SpringApplicationBuilder (org.springframework.boot.builder)
<init>:87, SpringApplicationBuilder (org.springframework.boot.builder)
findOne:114, NativeEnvironmentRepository (org.springframework.cloud.config.server.environment)
findOne:45, CompositeEnvironmentRepository (org.springframework.cloud.config.server.environment)
findOne:53, EnvironmentEncryptorEnvironmentRepository (org.springframework.cloud.config.server.environment)
labelled:107, EnvironmentController (org.springframework.cloud.config.server.environment)
defaultLabel:96, EnvironmentController (org.springframework.cloud.config.server.environment)
```

**Comment by spencergibb** [comment] 2017-11-29 17:30
@loicoudot thanks for the detailed analysis!

Can you confirm if there is a leak running an executable jar, rather than war?

> Until spring-cloud-config use a new SpringApplicationBuilder for each request, there will be some memory leaks.

Can you expound more? `NativeEnvironmentRepository.findOne()` is called for each request, is it not?

**Comment by loicoudot** [comment] 2017-11-30 08:09
@spencergibb 
> Can you confirm if there is a leak running an executable jar, rather than war?

Good catch, when using Spring uber jar package, java use `file:` protocol to access files inside the uber jar => no memory leak.
We can use jar package instead of war for the spring-cloud-config server and solve our problem !

> Can you expound more? NativeEnvironmentRepository.findOne() is called for each request, is it not?

Yes `NativeEnvironmentRepository.findOne()` is called for each request, so a new `SpringApplicationBuilder` instance is created which create the leak. What I understand from the code, is that we build a new `SpringApplicationBuilder` to have an isolated `Environnement` which are populated with the configuration before sending to the client. I don't know enough Spring and if it's possible to create an isolated `Environnement` without creating a new `SpringApplicationBuilder` ?

**Comment by marcingrzejszczak** [comment] 2018-07-13 20:04
Is it still a problem with Finchley.RELEASE?

**Comment by spencergibb** [comment] 2018-10-01 22:37
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-10-01 22:37 UTC
Labels: waiting for feedback
