### ISSUE TITLE
Spring-cloud-config-client and spring.profiles.include support

### ISSUE THREAD

**Issue by danielkwinsor** [spring-cloud/spring-cloud-config#847] opened 2017-11-11 00:31 UTC
Using spring-boot 1.5.7 and cloud-config-client 1.3.3
I have an application.yml, bootstrap.yml, and .mvn/maven.config
The bootstrap is
```
spring:
  application:
    name: name
  profiles:
    active: a, b, c
  cloud:
    config:
      label: label
```

An attempt was made to add spring.profiles.include=d in both bootstrap and application.yml, however, as per #367 this did not work.

Since the goal was to run a dev profile only when running spring-boot from maven, .mvn/maven.config added `-Dspring.profiles.include=d` which is the same as running spring-boot:run with the same command line arg.
With `spring.profiles.include=d`, the Environment.getActiveProfiles() (and /env endpoint) showed a, b, c, d yet the request to the config-server showed the client was requesting only /name/d/label, skipping a, b, c entirely.  For this reason I'm filing this separately from #367 

The desire is support for both options -- bootstrap.yml and command line --  to make the spring-boot app send a request to the config-server with both spring.profiles.active and spring.profiles.include profiles.

**Comment by marcingrzejszczak** [comment] 2018-07-13 20:22
Is the problem still there in Finchley.RELEASE?

**Comment by danielkwinsor** [comment] 2018-07-18 20:52
I just verified that yes, the problem is still there.  The /trace actuator endpoint on the config-server showed that by including `-Dspring.profiles.include=d` it removed (from the /appName/profiles/label request) the original profiles `a, b, c` and replaced it with just `d`

**Comment by ryanjbaxter** [comment] 2018-07-19 12:29
@danielkwinsor can you provide an app that reproduces the problem?

**Comment by spencergibb** [comment] 2019-02-11 15:21
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2019-02-11 15:21 UTC
Labels: feedback-provided
