### ISSUE TITLE
Properties are not overridden for specific profiles when spring.cloud.config.label includes non existing branch

### ISSUE THREAD

**Issue by Aloren** [spring-cloud/spring-cloud-config#1596] opened 2020-04-23 12:39 UTC
We have a service that is deployed to different environments. One of the environment requires different configuration. This is currently handled by adding a specific profile for service on this env. Our configurations are stored in Git the following way:
```
service
  - service.yml
  - service-global.yml
  - service-env2-overrides.yml
```

We have faced an issue with `spring.cloud.config.label` property breaking properties override mechanism. 
When `--spring.cloud.config.label=feature(_)already-deleted-branch,master` is set -- properties from `service-env2-overrides.yml` do not take any effect. And when `--spring.cloud.config.label=master,master` -- everything works as expected.

Not sure what might be an issue, please advise.

**Comment by ryanjbaxter** [comment] 2020-04-27 20:23
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spencergibb** [comment] 2021-03-30 17:55
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2021-03-30 17:55 UTC
Labels: feedback-provided
