### ISSUE TITLE
ConfigClientWatch did not work

### ISSUE THREAD

**Issue by surlymo** [spring-cloud/spring-cloud-config#791] opened 2017-09-12 13:55 UTC
i found that ConfigClientWatch#watchConfigServer had some problem:

```
@Scheduled(initialDelayString = "${spring.cloud.config.watch.initialDelay:180000}", fixedDelayString = "${spring.cloud.config.watch.delay:500}")
	public void watchConfigServer() {
		if (this.running.get()) {
			String newState = this.environment.getProperty("config.client.state");
                        String oldState = ConfigClientStateHolder.getState();
			if (stateChanged(oldState, newState)) {
				ConfigClientStateHolder.setState(newState);
				this.refresher.refresh();
			}
		}
	}
```
newState would not refresh when Spring Cloud Config Server's prop state updated, so newState always equals oldState. as a result, the config would not refresh.

**Comment by david1228** [comment] 2018-07-02 08:10
I also encountered this problem.
Do you know the reason for this problem?

**Comment by ryanjbaxter** [comment] 2018-07-02 23:31
Can you provide a sample that reproduces the problem?

**Comment by spencergibb** [comment] 2018-10-01 22:37
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-10-01 22:37 UTC
Labels: waiting for feedback

**Comment by spencergibb** [comment] 2018-12-18 14:57
@rahulsingh336 please don't comment on unrelated issues. Please ask on gitter
