### ISSUE TITLE
Hi! I have problem with @ConstructorBinding in bootstrap context. I use Kotlin

### ISSUE THREAD

**Issue by KirillKurdyukov** [spring-cloud/spring-cloud-config#2078] opened 2022-04-15 08:41 UTC
Cannot bind @ConfigurationProperties for bean 'ktor.client.core.configuration.KtorClientsPropertiesBootstrap'. Ensure that @ConstructorBinding has not been applied to regular bean

**Comment by KirillKurdyukov** [comment] 2022-04-15 08:45
```
client:
  application:
    server:
      url: application-context.ru
```
```
@ConstructorBinding
@ConfigurationProperties(prefix = "")
class KtorClientsPropertiesBootstrap(var client: Map<String, KtorClientProperties> = mapOf()) {
    fun toKtorClientsProperties() = KtorClientsProperties(mapOf("configService" to configService))
}

data class KtorClientProperties(
    val server: ServerSettings,
    val tvm: KtorClientAuth?,
    val tls: KtorTlsSettings?,
    val settings: KtorClientSettings?,
)

data class ServerSettings(val url: String)

data class KtorTlsSettings(
    val group: String = "",
    val trustAny: Boolean = false,
)

data class KtorClientAuth(
    val auth: KtorClientAuthTvm = KtorClientAuthTvm(),
)

data class KtorClientAuthTvm(
    val clientId: Int = -1,
)

data class KtorClientSettings(
    val expectSuccess: Boolean = true,
)
```

**Comment by KirillKurdyukov** [comment] 2022-04-15 08:48
https://github.com/spring-projects/spring-boot/issues/26203 maybe this issue not fixed?

**Comment by bas-kirill** [comment] 2022-04-15 08:50
I met with the same error

**Comment by ryanjbaxter** [comment] 2022-11-03 00:19
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment] 2022-11-10 00:21
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-11-17 00:21
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-11-17 00:21 UTC
Labels: waiting for feedback, feedback-reminder

**Comment by steklopod** [comment] 2022-11-20 18:14
I have the same issue after upgrade Spring Boot:


<img width="1092" alt="Снимок экрана 2022-11-20 в 19 04 14" src="https://user-images.githubusercontent.com/29500153/202918246-9a02a5a2-ad1e-464e-bff6-350db5cfe86a.png">

**Comment by ryanjbaxter** [comment] 2022-11-22 01:27
See https://github.com/spring-cloud/spring-cloud-config/issues/2078#issuecomment-1301515429

**Comment by mnorlin** [comment] 2022-11-25 21:36
Here is a repository with a minimal implementation that reproduces the problem:
https://github.com/mnorlin/issue-spring-cloud

The project is in the **/demoK** directory.
