### ISSUE TITLE
Unable to get the properties from Git Backend when using Spring Boot 2.4.2

### ISSUE THREAD

**Issue by gkgaurav31** [spring-cloud/spring-cloud-config#1772] opened 2020-12-15 18:29 UTC
I am trying to create a simple Spring Cloud Config server backend by GitHub Repository (public). The same configuration is working for Spring Boot 2.3.7 but not for Spring Boot 2.4.2. 

java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (Zulu 8.44.0.11-win64)-Microsoft-Azure-restricted (build 1.8.0_242-b20)
OpenJDK 64-Bit Server VM (Zulu 8.44.0.11-win64)-Microsoft-Azure-restricted (build 25.242-b20, mixed mode)

Repro steps:

- Create a Spring Boot project with Config Server dependency
- Add the following to application.properties:

  spring.application.name=config-server-server23
  server.port=8888
  spring.cloud.config.server.git.uri=https://github.com/gkgaurav31/config.git

Adding @EnableConfigServer annotation.

Output from Config Server when accessing: http://localhost:8888/default/env

With Spring Boot 2.3.8:

{"name":"default","profiles":["env"],"label":null,"version":"85c8f673c450ee944ad612a1371b17e570785a7b","state":null,"propertySources":[{"name":"https://github.com/gkgaurav31/config.git/application.properties","source":{"application.message":"Hello, from default!","message":"Hello from GitHub!"}}]}

With Spring Boot 2.4.2:

{"name":"default","profiles":["env"],"label":null,"version":"85c8f673c450ee944ad612a1371b17e570785a7b","state":null,"propertySources":[]}

1) Is there any other configuration required for Spring Boot 2.4.x
2) How can we determine what is wrong?

**Comment by spencergibb** [comment] 2020-12-15 19:01
https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#breaking-changes

Either use the new way of importing `spring.config.import=configserver:` in application.yml (not bootstrap) or add `spring-cloud-starter-bootstrap`.

**Comment by Mohammadpiran** [comment] 2020-12-17 00:04
> https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#breaking-changes
> 
> Either use the new way of importing `spring.config.import=configserver:` in application.yml (not bootstrap) or add `spring-cloud-starter-bootstrap`.

I am new in spring boot. Ihave same problem. Can you explain more. Tnx

**Comment by MohammadToficMohammad** [comment] 2020-12-19 21:46
I have the same issue , the problem in config server not in the client , so i do not think the previous answers will solve it , please we need help

**Comment by Mohammadpiran** [comment] 2020-12-20 06:57
I use spring version 2.4.2.snapshot  and my problem solved. I think there is problem in version of spring boot.

**Comment by Mohammadpiran** [comment] 2020-12-20 09:20
Config property source is empty. 
When i run config server in linux ubuntu my problem solved. I dont know what can be the problem reason.

**Comment by bberus** [comment] 2020-12-20 17:05
I think root cause of issue is described here (by me):
https://stackoverflow.com/questions/65371728/springboot-config-server-file-separator-issue

**Comment by spencergibb** [comment] 2020-12-20 17:21
Closing, those on windows follow #1774

**Closed by spencergibb** 2020-12-20 17:21 UTC
Labels: feedback-provided
