### ISSUE TITLE
NativeEnvironmentRepository,clean() method does not work on windows.

### ISSUE THREAD

**Issue by douglassparker** [spring-cloud/spring-cloud-config#168] opened 2015-06-05 17:38 UTC
NativeEnvironmentRepository,clean() method does not work on windows. E.g. spring.cloud.config.server.native.searchLocations=file:/app/config,
This code works on Unix or Linux, but not Windows:
if (normal.startsWith(pattern)
&& !normal.substring(pattern.length()).contains("/"))
{ matches = true; break; }
normal = C:\app\config\demo.yml
pattern = C:/app/config/
Entering the property in the Windows format does not fix the issue.
normal is calculated by:
String normal = name;
if (normal.startsWith("file:"))
{ normal = new File(normal.substring("file:".length())).getAbsolutePath(); }
On windows, getAbsolutePath() returns the path using a back slash for the path delimiter.

**Comment by spencergibb** [comment] 2015-06-05 17:42
Closing as duplicate of #164

**Closed by spencergibb** 2015-06-05 17:42 UTC
Labels: duplicate
