### ISSUE TITLE
ConfigServerInstanceProvider$Function has not been registered in kubernetes

### ISSUE THREAD

**Issue by mschneid0207** [spring-cloud/spring-cloud-config#2009] opened 2021-11-30 19:21 UTC
Hello together,

I migrated from Spring Boot 2.3.2 to 2.5.6. 
When starting up the services and using eureka as service discovery everything is running fine. All my client services are finding correctly the spring cloud config service and fetching their configurations from it. 
But when I use the service discovery from spring cloud kubernetes (spring-cloud-starter-kubernetes-all) I always getting the following error.

I always get the following error.
java.lang.IllegalStateException: org.springframework.cloud.config.client.ConfigServerInstanceProvider$Function has not been registered
	at org.springframework.boot.DefaultBootstrapContext.lambda$get$1(DefaultBootstrapContext.java:88)
	at org.springframework.boot.DefaultBootstrapContext.getOrElseThrow(DefaultBootstrapContext.java:109)
	at org.springframework.boot.DefaultBootstrapContext.get(DefaultBootstrapContext.java:88)
	at org.springframework.cloud.config.client.ConfigServerConfigDataLocationResolver.lambda$resolveProfileSpecific$8(ConfigServerConfigDataLocationResolver.java:196)
........

Here is my config in the application.yml of one of my client services (e.g. customer-service).

```
spring:
  application:
    name: customer-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
      retry:
        max-attempts: 10
      fail-fast: true
```
I tested it with spring cloud dependencies 2020.0.0 - 2020.0.4. But I am always getting the following error.
Also I tested with different version of spring-cloud-starter-kubernetes-all.
I always getting the same error.

Thanks a lot for your support.

Regards
Markus

**Comment by vananiev** [comment] 2022-04-04 11:42
I've got same exception with spring-boot 2.6.5 + Spring Cloud 2020.5.

**Comment by ryanjbaxter** [comment] 2022-04-04 23:51
Can you please try Spring Cloud 2021.0.1?

**Comment by vananiev** [comment] 2022-04-05 12:30
Yes. Spring Boot 2.6.6 + Spring Cloud 2021.0.1 works

**Comment by ryanjbaxter** [comment] 2022-04-05 15:17
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by vananiev** [comment] 2022-04-05 18:14
Sorry, can't reproduce on "complete, minimal, verifiable sample". My app with Config Server 2020.0.5 configures `configPath` in Eureka metadata if `spring.cloud.config.server.prefix` was set, but Config Server 2021.0.1 doesn't configure `configPath`.

I need more time to explore, come back later.

**Comment by vananiev** [comment] 2022-04-05 19:53
I found the problem.

Spring Boot `2.5.12` + Spring Cloud `2020.0.5` + Spring Cloud Starter Netflix Ribbon `2.2.7` + Ribbon Eureka `2.3.0` leads to this order in method calls
1. EurekaClientConfigServerAutoConfiguration:41 (adds `configPath` to metadata)
2. DicscoveryClient:338 (client registeration)

This is ok, `configPath` appears in client's Eureka metadata.

Now if I update only Spring Boot to `2.6.6` and Spring Cloud to `2021.0.1`, then app starts, but calls is swapped
1. DicscoveryClient:338 (client registeration)
2. EurekaClientConfigServerAutoConfiguration:41  (adds `configPath` to metadata)

So, there is no `configPath` in clients's Eureka metadata.

Now if I update ribbon's version too (finally I've got Spring Boot `2.6.6` + Spring Cloud `2021.0.1` + Spring Cloud Starter Netflix Ribbon `2.2.10` + Ribbon Eureka `2.7.18`), methods is called in right order
1. EurekaClientConfigServerAutoConfiguration:41
2. DicscoveryClient:338

`configPath` again appears in client's Eureka metadata.

**Comment by ryanjbaxter** [comment] 2022-04-05 23:59
Ribbon is no longer supported, you configuration is invalid
https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#breaking-changes-1

**Comment by alejandroMartin** [comment] 2022-05-13 07:38
Hi, 
I have the same problem with Spring Boot 2.6.7 and Spring Cloud 2021.0.2 using spring-cloud-starter-kubernetes-fabric8. [Here](https://github.com/alejandroMartin/configClientk8s) is a minimal sample application I've created from Spring Initializr that reproduces the problem. I hope may help.

**Comment by ryanjbaxter** [comment] 2022-05-13 20:48
Please provide instructions on how to reproduce the problem with the sample

**Comment by alejandroMartin** [comment] 2022-05-17 07:13
Sorry, I get the error when application starts, so just run the default [test class](https://github.com/alejandroMartin/configClientk8s/blob/master/src/test/java/com/example/configClientk8s/ConfigClientk8sApplicationTests.java).

**Comment by ryanjbaxter** [comment] 2022-05-25 17:43
I created an issue in Spring Cloud Kubernetes
https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1021

We will need to do some work there in order to support this

**Comment by ryanjbaxter** [comment] 2023-08-04 10:27
Please try 2021.0.8

**Comment by ryanjbaxter** [comment] 2023-08-04 10:27
This was fixed by https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1021

**Closed** 2023-08-04 10:27 UTC
Labels: feedback-provided
