### ISSUE TITLE
Bug with use of Eureka First Bootstrap mode

### ISSUE THREAD

**Issue by edethoor** [spring-cloud/spring-cloud-config#231] opened 2015-09-18 13:09 UTC
We have implemented a Eureka server and our config server registers well on this one.

When we set up one of our applications to discover the address of the config server via Eureka, everything goes well.

But I noticed that thereafter our application no longer sends herthbeat to the Eureka server, which has the effect that after a while, Eureka believes that this application is no longer available.

If I disable the discovery of the config server through Eureka and I specify the url directly, our application registers well on the Eureka server and regularly sends herthbeats to this one.

I'm using Spring Boot 1.3.0.M5 and  Spring Cloud 1.1.0.M1.

**Comment by dsyer** [comment] 2015-09-23 12:05
I believe this is actually a duplicate of https://github.com/spring-cloud/spring-cloud-netflix/issues/421

**Closed by dsyer** 2015-09-23 12:05 UTC
Labels: bug
