### ISSUE TITLE
pause and resume not working with spring.cloud.bus.enabled=true

### ISSUE THREAD

**Issue by jagan23527001** [spring-cloud/spring-cloud-config#1207] opened 2018-11-30 20:08 UTC
version - spring-cloud-context/1.3.2.RELEASE

we are trying to pause and resume (kafka beans) by enabling the endpoint of the below properties

endpoints.pause.enabled=true
endpoints.restart.enabled=true
endpoints.resume.enabled=true
endpoints.restart.sensitive=true
endpoints.resume.sensitive=true
endpoints.pause.sensitive=true
endpoints.beans.sensitive=false
endpoints.metrics.sensitive=false
endpoints.info.sensitive=false
endpoints.mappings.sensitive=false
endpoints.health.sensitive=false
endpoints.env.sensitive=false
endpoints.refresh.sensitive=false
management.security.enabled=true

This is working,  if we keep these 3 below properties as false.

spring.cloud.bus.amqp.enabled=false
spring.cloud.bus.enabled=false
spring.cloud.config.enabled=false

When we keep "true" the pause and resume is not working.

Any idea / thought why is it not working , really help us.

**Comment by spencergibb** [comment] 2018-11-30 21:05
Doesn't make much sense as they aren't related.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by jagan23527001** [comment] 2018-11-30 21:37
Let me get it in a sample codes

**Comment by jagan23527001** [comment] 2018-12-05 17:39
any udpdate 

> Doesn't make much sense as they aren't related.
> 
> Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spencergibb** [comment] 2019-01-31 21:07
I don't see any messages being processed at all, so I'm not sure how to replicate it.

**Comment by spring-issuemaster** [comment] 2019-02-07 21:08
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-02-14 21:11
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-02-14 21:11 UTC
Labels: feedback-reminder, waiting for feedback
