### ISSUE TITLE
S3 bucket bug make it useless to use it as backend ! 

### ISSUE THREAD

**Issue by avnerstr** [spring-cloud/spring-cloud-config#1886] opened 2021-05-23 17:41 UTC
I also see this problem. Is someone working to solve this bug ?! it's totally wrong behaviour and it's different than the git behaviour. Is there a workaround to this issue?

_Originally posted by @avnerstr in https://github.com/spring-cloud/spring-cloud-config/issues/1611#issuecomment-846594458_

**Comment by avnerstr** [comment] 2021-05-23 17:45
This is not enhancement. Due to this bug, we can't work with the S3 bucket.

there is also stackoverflow issue about it:

[](https://stackoverflow.com/questions/61251423/cant-get-hierarchic-properties-by-s3-backend-spring-config-server)

**Comment by avnerstr** [comment] 2021-05-23 17:45
https://stackoverflow.com/questions/61251423/cant-get-hierarchic-properties-by-s3-backend-spring-config-server

**Comment by jaganm2018** [comment] 2021-05-31 10:11
Can you share sample code at least to read {application}-{profile}.properties/yml?. Thanks in advance. 

No proper documentation from spring team.

**Comment by ryanjbaxter** [comment] 2021-06-01 15:48
Duplicate of  #1611

**Closed by ryanjbaxter** 2021-06-01 15:48 UTC
Labels: waiting-for-triage
