### ISSUE TITLE
Config server doesn't preserve quotes when resolving placeholders

### ISSUE THREAD

**Issue by tnaskali** [spring-cloud/spring-cloud-config#1413] opened 2019-06-28 07:43 UTC
In Spring Cloud config v.1.4.3.RELEASE (not tested with more recent versions), if a YAML property value is quoted and referenced through a placeholder, the quotes are not preserved after the config server performs placeholders resolution.
For example
```yaml
key1:
  key11: 'value1:'
  key12: ${key1.key11}
```
becomes after resolution
```yaml
key1:
  key11: 'value1:'
  key12: value1:
```
while you would expect
```yaml
key1:
  key11: 'value1:'
  key12: 'value1:'
```

**Comment by ryanjbaxter** [comment] 2019-07-08 14:47
I belive that is an old Edgware release.  The current release is Edgware.SR6 but this is going to reach end of life on August 1st.  I would suggest you upgrade to Greenwich.SR2 and try to reproduce the issue.

**Comment by spring-issuemaster** [comment] 2019-07-15 14:50
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-07-22 14:47
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-07-22 14:47 UTC
Labels: feedback-reminder, waiting-for-triage
