### ISSUE TITLE
endpoint /health : configServer DOWN

### ISSUE THREAD

**Issue by RaphC** [spring-cloud/spring-cloud-config#425] opened 2016-06-24 14:54 UTC
Hi,

I'm testing spring-cloud-config with an application. The boot of my app is ok and my props are correctly set (with a profile dev and a label which is a branchName defined in my bootstrap.yml file). But when I call the /health endpoint, my app returns the following result : 

```
{"status":"DOWN","application":{"status":"UP"},"configServer":{"status":"DOWN","error":"java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing"}}
```
In my configServer log I see

```
2016-06-24 16:44:05.017 DEBUG 10514 --- [qtp2130870843-20] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing GET request for [/application/dev/feature-piranas-support]
2016-06-24 16:44:05.018 DEBUG 10514 --- [qtp2130870843-20] s.w.s.m.m.a.RequestMappingHandlerMapping : Looking up handler method for path /application/dev/feature-piranas-support
2016-06-24 16:44:05.019 DEBUG 10514 --- [qtp2130870843-20] s.w.s.m.m.a.RequestMappingHandlerMapping : Returning handler method [public org.springframework.cloud.config.environment.Environment org.springframework.cloud.config.server.environment.EnvironmentController.labelled(java.lang.String,java.lang.String,java.lang.String)]
2016-06-24 16:44:05.019 DEBUG 10514 --- [qtp2130870843-20] o.s.web.servlet.DispatcherServlet        : Last-Modified value for [/application/dev/feature-piranas-support] is: -1
2016-06-24 16:44:05.021 DEBUG 10514 --- [qtp2130870843-20] .m.m.a.ExceptionHandlerExceptionResolver : Resolving exception from handler [public org.springframework.cloud.config.environment.Environment org.springframework.cloud.config.server.environment.EnvironmentController.labelled(java.lang.String,java.lang.String,java.lang.String)]: org.springframework.cloud.config.server.environment.NoSuchLabelException: No such label: feature-piranas-support
2016-06-24 16:44:05.021 DEBUG 10514 --- [qtp2130870843-20] .m.m.a.ExceptionHandlerExceptionResolver : Invoking @ExceptionHandler method: public void org.springframework.cloud.config.server.environment.EnvironmentController.noSuchLabel(javax.servlet.http.HttpServletResponse) throws java.io.IOException
```

It seems in this case that {application} is not well replaced

Here is the log in the configServer on startup

```
2016-06-24 16:46:34.941 DEBUG 10514 --- [qtp2130870843-19] s.w.s.m.m.a.RequestMappingHandlerMapping : Looking up handler method for path /gloud/dev/feature-piranas-support
```

As you can see on start this is the real application name which set whereas on /health call configServer receive 'application'.

Regards

**Comment by spencergibb** [comment] 2016-06-24 15:04
Duplicate of #269

**Closed by spencergibb** 2016-06-24 15:04 UTC

**Comment by RaphC** [comment] 2016-06-24 15:06
Thanks @spencergibb.
