### ISSUE TITLE
config-server reports "No such label: xxx" though the label exists

### ISSUE THREAD

**Issue by devtdeng** [spring-cloud/spring-cloud-config#1367] opened 2019-04-28 21:15 UTC
Bug report

For example,  with tag named '2.0' and branch named 'release/2.0' (2.0 can be replaced with any string),  configure the config server associated to label `2.0`, config-server will report "No such label: 2.0", though it exists. 

```
   2019-04-23T23:15:06.06+0200 [APP/PROC/WEB/0] OUT 2019-04-23 21:15:06.066  WARN 16 --- [nio-8080-exec-4] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.cloud.config.server.environment.NoSuchLabelException: No such label: 2.0]
   2019-04-23T23:15:06.07+0200 [RTR/0] OUT config-7ed691fa-8c89-4157-8e95-f2b401799629.cfapps-17.haas-59.pez.pivotal.io - [2019-04-23T21:15:05.267+0000] "GET /consumer-demo/production,cloud HTTP/1.1" 404 0 149 "-" "Java/1.8.0_192" "10.193.82.250:57458" "10.193.82.17:61046" x_forwarded_for:"10.193.82.16, 10.193.82.250" x_forwarded_proto:"https" vcap_request_id:"fcfd09a9-2da5-4db5-7924-c7be586581d0" response_time:0.809769391 app_id:"a80e7866-48ff-47eb-b86c-4082bc0a8788" app_index:"0" x_b3_traceid:"07be48df6c38de42" x_b3_spanid:"07be48df6c38de42" x_b3_parentspanid:"-"
```

**Comment by ryanjbaxter** [comment] 2019-04-29 14:13
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-05-06 14:13
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-24 15:02
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-07-01 15:02
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-07-01 15:02 UTC
Labels: feedback-reminder, waiting for feedback
