### ISSUE TITLE
Spring boot cloud jms client

### ISSUE THREAD

**Issue by sankintoo** [spring-cloud/spring-cloud-config#889] opened 2018-01-24 09:19 UTC
Should the spring boot cloud config client be always a Rest client?. I have a Jms spring boot config client. The properties @Values are null when it fetches from spring cloud config server. It works for Rest client. How to make it work. Could you please suggest.

**Comment by ryanjbaxter** [comment] 2018-01-24 12:42
Can you provide a sample that reproduces the problem?

**Comment by sankintoo** [comment] 2018-01-24 13:18
Please fined the file attached.

[csi-abstimmung-service.zip](https://github.com/spring-cloud/spring-cloud-config/files/1659921/csi-abstimmung-service.zip) (the client client)
[csi-configuration-service.zip](https://github.com/spring-cloud/spring-cloud-config/files/1659923/csi-configuration-service.zip) (the config server)

[abstimmung-dev.zip](https://github.com/spring-cloud/spring-cloud-config/files/1659938/abstimmung-dev.zip) (the property file)

**Comment by sankintoo** [comment] 2018-01-24 13:26
[csi-abstimmung-service.zip](https://github.com/spring-cloud/spring-cloud-config/files/1659957/csi-abstimmung-service.zip)  (The config client jms)

[csi-configuration-service.zip](https://github.com/spring-cloud/spring-cloud-config/files/1659958/csi-configuration-service.zip) (The Config server)
[abstimmung-dev.zip](https://github.com/spring-cloud/spring-cloud-config/files/1659959/abstimmung-dev.zip) (The property file)

**Comment by spencergibb** [comment] 2018-01-30 00:17
I'm unable to reproduce your problem with your code.

http://localhost:8091/env
```
  "profiles": [
    "dev"
  ],
  "configService:file:./config/abstimmung-dev.properties": {
    "message": "csi_ptt_out",
    "ptt.outqueue": "csi_ptt_out"
  },
```

http://localhost:8091/message
```
csi_ptt_out
```

**Comment by sankintoo** [comment] 2018-01-31 20:47
Thank you. That is not that my question is.
 I know it work when it is requested from RestContrroller or from browser.
It is not working for Jms client.
 Please see the jms code snippet, The @Value is null when referenced in jms
client.
Could you please assist.


On Jan 30, 2018 01:17, "Spencer Gibb" <notifications@github.com> wrote:

I'm unable to reproduce your problem with your code.

http://localhost:8091/env

  "profiles": [
    "dev"
  ],
  "configService:file:./config/abstimmung-dev.properties": {
    "message": "csi_ptt_out",
    "ptt.outqueue": "csi_ptt_out"
  },

http://localhost:8091/message

csi_ptt_out

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spring-cloud/spring-cloud-config/issues/889#issuecomment-361432465>,
or mute the thread

**Comment by spencergibb** [comment] 2018-01-31 21:15
I have no way to test the jms client.
Of course `AbstimmungMsgReceiver.csiPttOutQueue` will be null in the constructor, what else could it be?

If I add the following to `AbstimmungMsgReceiver`
```
   @PostConstruct
   public void init() {
       System.out.println("init csiPttOutQueue :" + csiPttOutQueue);
   }
```
I see
```
init csiPttOutQueue :csi_ptt_out
```

**Comment by spencergibb** [comment] 2019-02-11 15:20
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2019-02-11 15:20 UTC
Labels: feedback-provided
