### ISSUE TITLE
Integration aws vault and aws s3 config server issue

### ISSUE THREAD

**Issue by jaganm2018** [spring-cloud/spring-cloud-config#1921] opened 2021-06-25 20:12 UTC
Issue: integrating aws vault and aws s3 config server. 
exception: The bean 'configTokenProvider', defined in class path resource [org/springframework/cloud/config/server/config/VaultConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/cloud/config/server/config/EnvironmentRepositoryConfiguration$DefaultConfigTokenProvider.class] and overriding is disabled.

**Comment by ryanjbaxter** [comment] 2021-07-01 17:59
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by jaganm2018** [comment] 2021-07-02 09:09
It’s working now with integration of vault and config-server with below dependencies.
Here is my changes ..
1. Added spring cloud config and vault dependencies
2. Bootstrap file with config server aws s3 and cloud config server vault and cloud vault.
my concern: in that bootstrap , I added vault configuration in both spring cloud vault and spring cloud config server vault also. Is there any way we can skip spring cloud config server vault configuration..

please check and suggest me. Added screenshot of bootstrap and dependencies along with this message. 

Appreciate your help and responding. 
![Uploading A018230F-6666-47A6-AECA-4BE3B27B41CF.jpeg…]()

**Comment by jaganm2018** [comment] 2021-07-02 09:09
![257ED26F-BFBB-4F0D-96D4-CC8D0392D1C7](https://user-images.githubusercontent.com/84048983/124251267-5927bb80-db43-11eb-8fc5-a8cb5bca05a7.jpeg)

**Comment by jaganm2018** [comment] 2021-07-02 09:13
![Uploading E08B7E45-498E-47BE-ACFA-5A3D75685A8B.jpeg…]()

**Comment by jaganm2018** [comment] 2021-07-02 09:14
![Uploading F81B4EDF-C2D4-4F31-9FC5-44EC9CF5FB78.jpeg…]()

**Comment by ryanjbaxter** [comment] 2021-07-02 13:17
https://github.com/spring-cloud/spring-cloud-config/issues/1921#issuecomment-872442734

**Comment by jaganm2018** [comment] 2021-07-02 13:46
I shared the dependencies and my sample bootstrap yml. Still not able to provide solution then I will share the code to you?. Hope you can answer with above one. Please let me know. Thanks a lot.

**Comment by ryanjbaxter** [comment] 2021-07-06 14:46
Yes please create a sample in either a Git repo or attach it as a zip as my comment above stated

**Comment by spring-cloud-issues** [comment] 2021-07-13 14:49
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-07-20 14:48
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-07-20 14:48 UTC
Labels: feedback-reminder, waiting for feedback
