### ISSUE TITLE
It can bring properties from database table?

### ISSUE THREAD

**Issue by verystrongjoe** [spring-cloud/spring-cloud-config#205] opened 2015-07-30 04:26 UTC
I asked this question through stackoverflow site. 
http://stackoverflow.com/questions/30254786/spring-cloud-config-environment-repository-has-a-database

But nobody doesn't answer my question. In the README file of it, It is written like the followings.
```
Spring Cloud Config Server pulls configuration for remote clients from a git repository (which must be provided):
```

Maybe I can't understand of it. But I want it to read the properties from database and manage in the Spring Cloud Server. And Spring Cloud  Clients read this properties from the server.

Is it impossible or  wrong way?

**Comment by spencergibb** [comment] 2015-07-30 06:03
Closed, duplicate of #203

**Closed by spencergibb** 2015-07-30 06:03 UTC
