### ISSUE TITLE
spring.cloud.config.server.git.username vs spring.cloud.config.server.git.use

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-config#1448] opened 2019-08-18 03:17 UTC
Thanks for raising a Spring Cloud issue. What sort of issue are you raising?

Question

Which property to use: 
spring.cloud.config.server.git.username=xxx
or
spring.cloud.config.server.git.user=xxx

Bug report
The doc suggest to use spring.cloud.config.server.git.username= but it is not working
the property spring.cloud.config.server.git.user is flagged as Cannot resolve configuration property 'spring.cloud.config.server.git.user', but this one is working.

  <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-server</artifactId>
        </dependency>
 <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Greenwich.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.7.RELEASE</version>
        <relativePath/>
    </parent>

**Comment by ryanjbaxter** [comment] 2019-08-19 14:36
The right property appears to be `username` in the code

https://github.com/spring-cloud/spring-cloud-config/blob/v2.1.3.RELEASE/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/support/AbstractScmAccessorProperties.java#L48

Can you provide a sample that reproduces the problem?

**Comment by spring-issuemaster** [comment] 2019-09-02 14:38
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-09-02 14:38 UTC
Labels: feedback-reminder, waiting for feedback
