### ISSUE TITLE
@RefreshScope @Primary has a bug with the combined use

### ISSUE THREAD

**Issue by kkrgwbj** [spring-cloud/spring-cloud-config#1101] opened 2018-08-03 05:54 UTC
`version:2.0.0`
```
@Primary
    @org.springframework.cloud.context.config.annotation.RefreshScope
    @Bean
    @ConfigurationProperties(prefix = "app.datasource.first")
    public DataSource primaryDataSource(){
        return new HikariDataSource();
    }
 @Bean
    @ConfigurationProperties(prefix = "app.datasource.second")
    public DataSource secondDataSource() {
        return new HikariDataSource();
    }
 ```
 i start the project.have a error.
 ```
 nested exception is java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
 ```
 when i remove the @RefreshScope
 i start is success

**Comment by ryanjbaxter** [comment] 2018-08-06 14:01
Does it work with Edgware.SR4?  If so can you provide a project that reproduces the error?

**Comment by spring-issuemaster** [comment] 2018-10-01 22:30
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2018-10-01 22:30 UTC
Labels: waiting for feedback
