### ISSUE TITLE
Error with spring cloud zookeeper

### ISSUE THREAD

**Issue by ExtremeYu** [spring-cloud/spring-cloud-config#1020] opened 2018-05-19 08:31 UTC
if i set the setting in the application.properties ,the spring boot will not find the config-server via zookeeper but use default _localhost:8888_ instead,while i put the settings into bootstrap.yml ,the spring boot will failed to start due to no **UnsatisfiedDependencyException**

here is the detail:org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'discoveryClientConfigServiceBootstrapConfiguration': Unsatisfied dependency expressed through field 'instanceProvider'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'configServerInstanceProvider' defined in org.springframework.cloud.config.client.DiscoveryClientConfigServiceBootstrapConfiguration: Unsatisfied dependency expressed through method 'configServerInstanceProvider' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.client.discovery.DiscoveryClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
discoveryClientConfigServiceBootstrapConfiguration
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'configServerInstanceProvider' defined in org.springframework.cloud.config.client.DiscoveryClientConfigServiceBootstrapConfiguration: Unsatisfied dependency expressed through method 'configServerInstanceProvider' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.client.discovery.DiscoveryClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
Error creating bean with name 'discoveryClientConfigServiceBootstrapConfiguration': Unsatisfied dependency expressed through field 'instanceProvider'
field 'instanceProvider'

![a0ntnegqz3jgh 1 vy tb](https://user-images.githubusercontent.com/16620268/40266645-ea70126c-5b81-11e8-8752-50b19f8b5654.png)
![7pt y hahyipvl kg1 8l](https://user-images.githubusercontent.com/16620268/40266651-f0fb679e-5b81-11e8-8973-9b0ff999ed95.png)

![dtjz6yy04x3nux 23t qs2e](https://user-images.githubusercontent.com/16620268/40266659-047e1d0c-5b82-11e8-902d-aa01e6b9c137.png)

**Comment by ExtremeYu** [comment] 2018-05-19 08:35
in a word ,there is a bug with zookeeper

**Comment by indraneelb1903** [comment] 2018-05-19 13:27
Have u got the spring cloud zookeeper dependency in your pom.xml?

**Comment by indraneelb1903** [comment] 2018-05-19 13:27
Can u post a minimal,verifiable sample which reproduces the error?

**Comment by indraneelb1903** [comment] 2018-05-19 13:32
https://github.com/spring-cloud/spring-cloud-zookeeper/issues/159

**Comment by ExtremeYu** [comment] 2018-05-21 02:30
[workspace.zip](https://github.com/spring-cloud/spring-cloud-config/files/2021017/workspace.zip)
@indraneelb1903 

Hi,this is the demo project which reproduce the error.
the app project is the demo service ,config is the config server

**Comment by indraneelb1903** [comment] 2018-05-21 04:44
I will take a look tomorrow, and as @spencergibb as indicated on that thread, there might be some need for refactoring the code, to fix this.

**Comment by ryanjbaxter** [comment] 2018-05-21 23:39
Closing since this appears to be a problem with zookeeper

**Closed by ryanjbaxter** 2018-05-21 23:39 UTC
