### ISSUE TITLE
spring-cloud-config match resources but doesn't return the config to the client

### ISSUE THREAD

**Issue by EdouardBavoux** [spring-cloud/spring-cloud-config#2035] opened 2022-01-20 11:11 UTC
https://stackoverflow.com/questions/70782829/spring-cloud-config-match-resources-but-doesnt-return-the-config-to-the-client

Spring cloud config server handles partially the windows path (As shown in the debug logs, the .yml files are found and loaded correctly). The failure occurs almost at the end of the process, in the `clean()` function of `NativeEnvironmentRepository `class : Before sending the response to the config client, this function compares the location of the yml files to correct "patterns path", and this is where windows path are not handled correctly. (Locations are computed and mixes the two kinds of slashs : `C:\Users\Edouard\myconfig/myapp/`)

Maybe it would be a good idea that spring cloud config throw a proper error, or handles it properly ?

Thanks for your work !

**Comment by ryanjbaxter** [comment] 2022-01-21 01:45
thanks @EdouardBavoux!

Would you be able to create a PR with a unit test that reproduces or shows the failure?

**Comment by spring-cloud-issues** [comment] 2022-02-04 01:04
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-02-04 01:49
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-02-04 01:49 UTC
Labels: waiting for feedback, feedback-reminder

**Comment by thundur** [comment] 2022-02-09 09:38
Sort for the delay. I can confirm that this issue does not occur in spring-cloud-config-server 3.0.6 and 3.1.0.
