### ISSUE TITLE
Spring Cloud Config with JDBC backend dosn't support all HTTP service's resources

### ISSUE THREAD

**Issue by shaikezam** [spring-cloud/spring-cloud-config#2047] opened 2022-02-09 12:19 UTC
**Describe the bug**
I've create two projects:

1. Spring Cloud Config Server with H2 database as a backend
2. Spring Boot simple app that acts as a Spring Cloud Config Client.
Fetch properties & auto refresh working great,

This is the properties table:
![image](https://user-images.githubusercontent.com/16984302/153198971-6193a5cc-71f5-4727-86e4-9037433835ed.png)

Once I navigate to `http://localhost:8888/client/dev/latest` I get:

```
{
	"name": "client",
	"profiles": ["dev"],
	"label": "latest",
	"version": null,
	"state": null,
	"propertySources": [{
		"name": "client-dev",
		"source": {
			"my.value": "Hello world"
		}
	}]
}
```

According to the [doc](https://cloud.spring.io/spring-cloud-config/reference/html/#_quick_start):
![image](https://user-images.githubusercontent.com/16984302/153199491-673f93e4-969d-4f56-9f2b-3f2c00380908.png)

And if I navigate to `http://localhost:8888/client-dev.json` I get an empty {} (the same for yml or properties - just an empty response)

Any help how to fetch an entire application configuration for specific profile?

Thanks!

**Comment by ryanjbaxter** [comment] 2022-02-09 21:06
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by shaikezam** [comment] 2022-02-10 07:01
Hi @ryanjbaxter thanks.
Not sure if this is relevant, but this is the Git Hub repo - https://github.com/shaikezam/spring-cloud-config-jdbc

**Comment by ryanjbaxter** [comment] 2022-02-10 16:33
I cannot get the config server to start successfully, can you please provide a minimal example that demonstrates the problem and instructions on how to reproduce the problem with the example

**Comment by shaikezam** [comment] 2022-02-11 06:28
Hi @ryanjbaxter 
I added a `README` file https://github.com/shaikezam/spring-cloud-config-jdbc/blob/master/README.md

**Comment by ryanjbaxter** [comment] 2022-02-15 01:27
Duplicate of https://github.com/spring-cloud/spring-cloud-config/issues/2020

**Closed by ryanjbaxter** 2022-02-15 01:27 UTC
Labels: feedback-provided

**Comment by shaikezam** [comment] 2022-02-15 06:27
Thanks @ryanjbaxter 

It's still didn't fetch me the URL of /{application}-{profile}.properties (/{label}/{application}-{profile}.json working)

**Comment by ryanjbaxter** [comment] 2022-02-15 10:20
I know I closed this because it is the same problem as another issue already open

**Comment by shaikezam** [comment] 2022-02-15 10:25
Thanks @ryanjbaxter 
Any estimation when this will fixed?

**Comment by ryanjbaxter** [comment] 2022-02-15 11:36
I'm going to take a look at it today.  There is a workaround in the issue I referenced to change the matching algorithm

**Comment by shaikezam** [comment] 2022-02-15 12:48
Thanks @ryanjbaxter 
The workaround `spring.mvc.pathmatch.matching-strategy=ant_path_matcher` still didn't resolved the URL of `/{application}-{profile}.properties`

**Comment by ryanjbaxter** [comment] 2022-02-15 14:18
I added `spring.mvc.pathmatch.matching-strategy=ant_path_matcher` to the server in your sample and went to http://localhost:8888/teva/client-dev.properties and got the properties

**Comment by shaikezam** [comment] 2022-02-15 14:21
Thanks @ryanjbaxter
So as me, but it still didn't fetch me the URL of /{application}-{profile}.properties 
http://localhost:8888/client-dev.properties

**Comment by ryanjbaxter** [comment] 2022-02-15 14:27
Right you are missing the label in the URL

**Comment by shaikezam** [comment] 2022-02-15 16:36
Thanks @ryanjbaxter 

But I want properties of entire application + profile without label.
According to 
![image](https://user-images.githubusercontent.com/16984302/154106720-6837cb43-e2ed-4f9f-8f1b-69bcf94a8fc0.png)

You support /{application}-{profile}.properties

**Comment by ryanjbaxter** [comment] 2022-02-15 16:44
Without specifying a label the default will be `master` the label in your DB is `teva`, there is no data with a label `master`

**Comment by shaikezam** [comment] 2022-02-16 06:39
thanks @ryanjbaxter 
So it will be /master/client-dev.json when I execute the API http://localhost:8888/client-dev.properties?

**Comment by ryanjbaxter** [comment] 2022-02-16 10:21
Correct those would be equivalent
