### ISSUE TITLE
Spring Boot Admin or Spring Cloud Gateway could not fetch the dynamic Eureka clients when using Spring Cloud Config

### ISSUE THREAD

**Issue by andyzhaozhao** [spring-cloud/spring-cloud-config#1530] opened 2019-12-27 06:00 UTC
sample: https://github.com/andyzhaozhao/spring-cloud-config-issues-1530-sample
Everything runs well in  Spring Cloud G. The problem occured after we have upgraded to H.
### version
* Spring Cloud Hoxton.SR1
* Sping Boot 2.2.1

#### run without Spring Cloud Config
Everything runs well when did not using the Spring Cloud Config.   There's a Gateway microservice named "tdf-cloud-gateway" in front of other microservices such as "tdf-service-sys","tdf-service-route" and so on. "tdf-cloud-gateway" can auto proxy the new service registered in eureka. 
1. all the microservices Cluster runs well .
1. the tdf-cloud-gateway run on port 8090, http://localhost:8090/.....
1. create new a microservice named "tdf-service-sample" and runs on port 8050.
1. "tdf-cloud-gateway" can auto proxy "tdf-service-sample" by http://localhost:8090/tdf-service-sample/...

#### the problem description when using Spring Cloud Config
then "tdf-cloud-ateway" using "tdf-cloud-config" (a Spring Cloud Config service):
```
spring:
  profiles: dev
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 15
        max-interval: 3000
        multiplier: 1.3
      profile: dev
      discovery:
        enabled: true
        service-id: tdf-cloud-config
```
1. all the microservices Cluster runs well .
1. the tdf-cloud-gateway run on port 8090, http://localhost:8090/.....
1. create new a microservice named "tdf-service-sample" and runs on port 8050.
1. "tdf-cloud-gateway" **can not** auto proxy "tdf-service-sample" by http://localhost:8090/tdf-service-sample/...

#### conclusion
when using Spring Cloud Config, gateway **can not** auto proxy service added into microserice cluster dynamically . May be the problem is from Spring Cloud Config .

**Comment by andyzhaozhao** [comment] 2019-12-27 06:47
@spencergibb @dsyer @ryanjbaxter

**Comment by spencergibb** [comment] 2019-12-27 07:07
All on holiday, please be patient

**Comment by OLPMO** [comment] 2020-01-01 10:45
Cloud provide a minimal demo to reproduce the issue? @andyzhaozhao

**Comment by andyzhaozhao** [comment] 2020-01-06 02:00
> Cloud provide a minimal demo to reproduce the issue? @andyzhaozhao
I have seen the same problem in zuul: https://github.com/spring-cloud/spring-cloud-netflix/issues/3725. Are there any solutions for this issue? I guess Spring Cloud team prefer Consul than Spring Cloud Config?

**Comment by spencergibb** [comment] 2020-01-06 04:58
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2020-01-13 04:59
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-01-20 04:59
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by andyzhaozhao** [comment] 2020-04-26 10:29
@spencergibb 
I think this is a bug. I have writen a sample project for this issue: https://github.com/andyzhaozhao/spring-cloud-config-issues-1530-sample

**Comment by spencergibb** [comment] 2020-07-06 18:09
please retry with Hoxton.SR6. I believe there was a fix in gateway

**Comment by spring-issuemaster** [comment] 2020-07-13 18:11
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-07-20 18:12
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-07-20 18:12 UTC
Labels: feedback-reminder, waiting for feedback
