### ISSUE TITLE
combine configuration from multiple repositories

### ISSUE THREAD

**Issue by shalom938** [spring-cloud/spring-cloud-config#550] opened 2016-11-14 13:57 UTC
We are using config server for many services, we share common configuration for services by calling the files with different file name prefix and then we set multiple application names, for example:
```
myapp.yml
myapp-amsterdam.yml
myapp-bangkok.yml
kafka-producer.yml
kafka-producer-amsterdam.yml
kafka-producer-bangkok.yml
```

then in the service bootstrap.yml : 
```
spring.application.name=myapp,kafka-producer
spring.cloud.config.profiles=bangkok
```
 this works fine 

now we want a service to also be a cassandra-client, we could do the same but for various reasons we want the cassandra configuration to reside in a separate git repo, we tried by configuring the spring.cloud.config.server.git.repos with different patterns but it didn't work, config server would only load configuration from one git repo. so we actually want to combine configuration from different git repositories. or a repository url could be a list of repositories.

**Comment by spencergibb** [comment] 2016-11-15 02:27
Duplicate of #286?

**Comment by shalom938** [comment] 2016-11-15 10:57
Overrides is not a good solution for us. this is more a duplicate of https://github.com/spring-cloud/spring-cloud-config/issues/383.

**Comment by spencergibb** [comment] 2016-11-16 16:41
we already rejected #383

**Closed by spencergibb** 2016-11-16 16:41 UTC
