### ISSUE TITLE
Properties not resolved on FactoryBean initialization

### ISSUE THREAD

**Issue by D0rmouse** [spring-cloud/spring-cloud-config#1167] opened 2018-10-15 18:21 UTC
I've been using the Spring Cloud Config Client to connect to a config server on PCF. Unfortunately I'm using some legacy code that loads a keystore in an `afterPropertiesSet` of an `InitializeBean`, which is also a `FactoryBean`.

I noticed that when using the Config Client, the properties are not resolved even when they're available in an `application.properties`. Strange thing is that one of the properties, location of type `Resource` _is_ resolved.

My question is: Is this expected behavior and am I just missing something, or should all the properties be available when the bean is initialized? I'm guessing the latter so it seems like a bug to me and that's why I'm submitting it here.

Here's a link to a demo project illustrating the behavior:
https://github.com/D0rmouse/spring-cloud-config-1167

You'll see the following output when running the application: 

```
Location: class path resource [somekeystore.jks]
Password: [$, {, s, s, l, ., k, e, y, s, t, o, r, e, ., p, a, s, s, w, o, r, d, }]
Type: ${ssl.keystore.type}
```

After removing the `spring-cloud-starter-config` dependency and running again the output will be:
```
Location: class path resource [somekeystore.jks]
Password: [c, h, a, n, g, e, i, t]
Type: jks
```
I would expect both outputs to be the same.

**Comment by ryanjbaxter** [comment] 2018-10-25 18:42
I'm frankly a little confused about where `${ssl.keystore.password}` and `${ssl.kystore.type} are coming from since the bean definition does not even contain these values.

**Comment by ryanjbaxter** [comment] 2018-10-25 18:50
@spencergibb @dsyer any thoughts?

**Comment by dsyer** [comment] 2018-10-25 19:30
> I'm frankly a little confused about where `${ssl.keystore.password}` and `${ssl.kystore.type}` are coming from since the bean definition does not even contain these values.

It’s in the XML (the bean definition). And it looks like it contains those placeholders.

**Comment by ryanjbaxter** [comment] 2018-10-25 23:32
> It’s in the XML (the bean definition). And it looks like it contains those placeholders.

@dsyer Now I feel like a dummy.  My IDE was being smart and automatically put the correct values in the editor instead of showing me the real values.  So I never saw the properties in the XML file.  At least that makes more sense now :)

> I’m not sure it’s even anything to do with spring cloud.

Without Spring Cloud Config on the classpath it works as expected.

It seems to have something to do with implementing `FactoryBean`, if the class does not implement that interface the properties seems to resolve fine.

**Comment by dsyer** [comment] 2018-10-26 06:32
I see. It's this code in `RefreshAutoConfiguration`:

```java
				if (this.environment == null && registry instanceof BeanFactory) {
					this.environment = ((BeanFactory) registry)
							.getBean(Environment.class);
				}
```

That looks like a really bad thing to do because `getBean(Class)` causes a huge instantiation cascade of all `FactoryBeans`. There must be a better way.

**Comment by D0rmouse** [comment] 2018-10-26 08:47
Thanks so far. Setting the `spring.cloud.refresh.enabled` property to `false` or disabling the `RefreshAutoConfiguration` is a work-around as long as refreshing is not needed.

**Comment by ryanjbaxter** [comment] 2018-10-26 15:06
This only is a problem in Finchley, Edgware releases work fine.

**Comment by ryanjbaxter** [comment] 2018-10-26 18:56
@D0rmouse see https://github.com/spring-cloud/spring-cloud-commons/pull/436.  You can try building and installing that branch and then using Finchley.BUIL-SNAPSHOT and seeing if it fixes the issue.  It appears to work for me.

**Comment by D0rmouse** [comment] 2018-10-26 19:37
I'm using `io.pivotal.spring.cloud:spring-cloud-services-starter-config-client` instead of `org.springframework.cloud:spring-cloud-starter-config` which seems to prevent me from disabling the `RefreshAutoConfiguration` on PCF, so I'm hoping your fix will work!

I'm from Europe, so it will be tomorrow before I'll test it. Will let you know asap.

**Comment by ryanjbaxter** [comment] 2018-10-27 00:59
You will have to switch to the spring cloud jars and not scs.

**Comment by D0rmouse** [comment] 2018-10-27 08:18
I can confirm the fix works on with the demo project with the Spring Cloud as well as the io.pivotal dependencies. 

When I deploy to PCF with the fix and use a PCF Config Server the properties are still not resolved when the FactoryBean is initialized.

Maybe I go for making the Config Server connection manually using only Spring Cloud dependencies and see what happens.

**Comment by ryanjbaxter** [comment] 2018-10-27 11:45
I cant say for sure what it happening on PCF.  In either case that is something you will need to talk to the SCS team about.  Thanks for testing the fix!

**Comment by ryanjbaxter** [comment] 2018-10-27 11:45
Fixed via 9b8a70e

**Closed by ryanjbaxter** 2018-10-27 11:45 UTC
Labels: bug, in progress

**Comment by dsyer** [comment] 2018-10-28 11:47
I couldn't reproduce your issue with remote configuration and a `FactoryBean` so I'm not really sure what to make of it, and I doubt that this is the right place to start looking for fixes. Could you make a really simple sample app that shows the problem?

**Comment by D0rmouse** [comment] 2018-10-28 12:14
When you take the [sample application](https://github.com/D0rmouse/spring-cloud-config-1167), start `ConfigServerApplication` and then start `DemoApplication` you'll see 

> c.c.c.ConfigServicePropertySourceLocator : Environment demoapp has 1 property sources with 3 properties.

before

> com.example.demo.KeyStoreFactoryBean     : Password: [$, {, s, s, l, ., k, e, y, s, t, o, r, e, ., p, a, s, s, w, o, r, d, }]

(of course, make sure @ryanjbaxter's fixed spring-cloud-context isn't on the classpath when running)

So the properties are loaded, but not available to `KeyStoreFactoryBean` when the `afterPropertiesSet` method is called.

This clearly illustrates the properties **could** be available to `KeyStoreFactoryBean` but somehow **aren't**.

I get that this may not be the place to address this issue, but what would be then? spring-framework?

Or should the advice be just to not use property driven `FactoryBean`s because there seems to be no way the system can guarantee the properties will be availble when they're loaded?

**Comment by D0rmouse** [comment] 2018-10-29 07:45
I have a feeling you haven't read what I posted, please re-read my previous two posts. I'm not talking about a new issue, but rather a different solution to this one.

I'm saying that Ryan's fix does fix the bug, you can read I've tested it myself, but probably it could be fixed more genericly. 

Now you've prevented an instantiation cascade, while it would be better to provide the properties to the `AbstractFactory` that instantiates the `FactoryBean`s, because clearly they are already loaded...

**Comment by dsyer** [comment] 2018-10-29 08:12
I certainly did read everything you wrote, but now I'm just confused. You seem to be saying that even with the newest snapshots you are seeing a problem that I can't reproduce. Please open an issue in spring-cloud-commons so we can continue the analysis.

**Comment by D0rmouse** [comment] 2018-10-29 08:43
No not with the newest snapshots... I'm talking about the unfixed situation and how the log output in that situation shows that it could be fixed in a different, more generic way,

**Comment by dsyer** [comment] 2018-10-29 09:01
I'm not sure I follow then (and nothing in the logs jumps out at me as wrong). We definitely needed to fix that cascade anyway, so what's wrong with the solution we have?

**Comment by D0rmouse** [comment] 2018-10-29 14:18
The logs (from the unfixed output) show me that properties are available before the `FactoryBean` is initialized, because they have been fetched from the Config Server, but somehow they are not available to the `FactoryBean`. This is wrong. 

The cascade fix is ok for this scenario, but it doesn't fix the root issue, which is what I stated above. It should work even with the cascade, because the properties should already be available.

**Comment by D0rmouse** [comment] 2018-10-29 14:34
Wow that's really easy. So you probably didn't even run the app and see that the properties are loaded before the bean is instantiated. You don't even believe me... 

Nevermind then.

**Comment by ryanjbaxter** [comment] 2018-10-29 15:04
Sorry we are very busy with many projects to maintain, we dont have time to run every single app and test every single thing.  I did not say I didnt believe you, I was just instructing you what the correct course of action is to move forward.

**Comment by dsyer** [comment] 2018-10-29 15:32
FWIW I ran it. I didn't see a problem. Seems like it's not really an issue to me. If you think it is then spring-cloud-commons is the place to discuss it.

**Comment by D0rmouse** [comment] 2018-10-29 17:08
I understand you're busy and appreciate the instruction and I'll take it up with the commons people.

I don't understand how it is you think that loading FactoryBeans without resolved properties while they clearly can be is not really an issue.

Any cascade triggered from anywhere too early will become an issue until this is addressed, as I've already encountered.

**Comment by spencergibb** [comment] 2018-10-29 17:18
Same folks, code just lives in Commons

**Comment by D0rmouse** [comment] 2018-12-18 11:47
Hi,

I've tested with the following versions. The issue is not resolved.

- Spring Boot 2.1.1.RELEASE
- Spring Cloud Greenwich.M3

I read Greenwich.M3 should contain spring-cloud-commons 2.1.0.M2, in which the issue should be resolved right?

I also the FactoryBean issue has become more of an issue in this release than it was before in my production project.

**Comment by ryanjbaxter** [comment] 2018-12-19 00:47
It is in there
https://github.com/spring-cloud/spring-cloud-commons/blob/v2.1.0.RC2/spring-cloud-context/src/main/java/org/springframework/cloud/autoconfigure/RefreshAutoConfiguration.java

But as we said above this is not the repo this issue, please open an issue in spring cloud commons.

**Comment by D0rmouse** [comment] 2018-12-19 08:54
Yes, but the demo project and the initial issue was submitted and solved here and this fix doesn't seem to work. This fix should at least fix the scenario in the demo project. It doesn't address the [real issue, which is already created in spring-cloud-commons](https://github.com/spring-cloud/spring-cloud-commons/issues/439).

**Comment by spencergibb** [comment] 2018-12-19 12:06
Then that is the issue to track
