### ISSUE TITLE
Native image with config client silently fails when fail-fast=true

### ISSUE THREAD

**Issue by MatthiasDrews** [spring-cloud/spring-cloud-config#2360] opened 2023-11-30 13:12 UTC
**Describe the bug**
When starting a Spring Cloud Config Client in a native image, having the environment variable `SPRING_CLOUD_CONFIG_FAIL_FAST=true`, the image fails silently without any message, even when the Config Server is available. 
With `SPRING_CLOUD_CONFIG_FAIL_FAST=false` the image starts successfully, and the logs show that the configuration was fetched from the Config Server.

I would expect that the image only fails, when no configuration can be fetched from the config server for whatever reason.

Is there some additional configuration needed on my side?

**Comment by ryanjbaxter** [comment] 2023-11-30 19:52
@OlgaMaciaszek is this something you have tried?  Any ideas?

**Comment by OlgaMaciaszek** [comment] 2023-12-01 11:29
Will take a look at it. Thanks.

**Comment by MatthiasDrews** [comment] 2024-02-15 07:02
Hi @OlgaMaciaszek . With `fail-fast` set to `true` and config-server being available, the startup failed.
Possibly the property source could not be located, this might be the reason for the startup failing. But without any output this is hard to detect or even fix from a user-perspective. So any output is crucial.

**Comment by OlgaMaciaszek** [comment] 2024-02-15 11:06
I was not able to reproduce the issue with config server available. Have you tried connecting to the same server without `fail-fast` set to `true`. Have you got any output from that?

**Comment by OlgaMaciaszek** [comment] 2024-02-15 14:50
Thanks for the information @MatthiasDrews; it's still probably something in  your environment causing the issue, since we could not replicated, but the output will be needed to determine what.

**Comment by OlgaMaciaszek** [comment] 2024-02-26 13:21
This is issue affects  not only Spring Cloud Config, but also Spring Boot. Closing in favour of https://github.com/spring-projects/spring-boot/issues/39742. @MatthiasDrews please see https://github.com/spring-projects/spring-boot/issues/39742#issuecomment-1961654290 for a workaround.r

**Closed by OlgaMaciaszek** 2024-02-26 13:21 UTC
Labels: closable

**Comment by MatthiasDrews** [comment] 2024-03-01 11:36
Thank you! The suggested workaround works for me, and I get logs now. 

The startup currently fails, because the `ConfigClientRetryBootstrapper` runs into a `NullPointerException`. I have `spring-retry` as a transitive dependency, which relies on reflection. This of course does not work in the native image. Probably I can find another workaround for this problem, now that the logs can be seen.

**Comment by OlgaMaciaszek** [comment] 2024-03-01 12:21
@MatthiasDrews   You might want to add some custom hints or report an issue with `spring-retry` if  some of the classes from that project do not register the required native hints.
