### ISSUE TITLE
[Issue] Spring Cloud Starter Config(spring cloud config client) prevents loading of vault secrets

### ISSUE THREAD

**Issue by karunatm** [spring-cloud/spring-cloud-config#2411] opened 2024-04-25 18:35 UTC
I have a Spring Cloud Config Server(pom: spring-cloud-config-server) up and running and loading all configured properties from the local repo. I also created a new spring cloud config client(pom: spring-cloud-starter-config). I'm using spring-cloud-starter-vault-config to read secrets from the hashicorp vault. Without using any of the above pom references on my standalone project, I'm able to successfully read the contents of hashicorp vault. But if I start using this server/client model, the client is able to retrieve properties from the config server but not from the configured vault. Any help is appreciated.

**Comment by ryanjbaxter** [comment] 2024-04-29 19:55
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment] 2024-05-06 19:59
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2024-05-13 19:59
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2024-05-13 19:59 UTC
Labels: feedback-reminder
