### ISSUE TITLE
active profile is not working via weblogic

### ISSUE THREAD

**Issue by tanujtripathi** [spring-cloud/spring-cloud-config#1486] opened 2019-10-03 10:59 UTC
I have a spring cloud config server(Spring boot application) that has client property files as:-
1. {application-name}.properties
2. {application-name}-dev.properties
3. {application-name}-prod.properties.  
NOTE: All of these files are in gitLab currently.

Ideally, when I run my client application with dev profile it should first search in **{application-name}-dev.properties** and if it is not found it should search in **{application-name}.properties**.

I am using weblogic and when i build a WAR of my client application by using **mvn clean install -P dev** that is with dev profile and deploying it in weblogic, client app is able to find the properties that resides in {application-name}.properties but not in **{application-name}-dev.properties**.

This means irrespective of which profile i give it always searches in {application-name}.properties.

Please help as to how achieve the above functionality of spring cloud config server in weblogic?

**Comment by ryanjbaxter** [comment] 2019-10-09 16:52
Doesnt sound like an issue specifically with running on WebLogic.  If you build the application as a jar does it behave differently?

**Comment by tanujtripathi** [comment] 2019-10-14 09:16
War or JAR it behaves the same. Only properties resides in {application-name}.properties are working.

**Comment by OLPMO** [comment] 2020-01-07 08:15
Could you provide a minimal demo that can reproduce the problem? @tanujtripathi

**Comment by spring-issuemaster** [comment] 2020-01-21 19:04
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-01-28 19:01
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-01-28 19:01 UTC
Labels: feedback-reminder, waiting for feedback
