### ISSUE TITLE
Spring cloud not reading config from provided git URI

### ISSUE THREAD

**Issue by tamal2401** [spring-cloud/spring-cloud-config#1449] opened 2019-08-18 19:46 UTC
I have provided git config as in bootstrap.yml but still its not reading the configs and there are no errors in the log. Not able to solve this issue.

Config --->

```
 server:
  port: 8080
spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tamal2401/Config-Server-Git.git
          username: #######@gmail.com
          password: ######
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
```

Logs are getting printed --->
```
2019-08-19 01:11:19.853  INFO 8208 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-08-19 01:11:19.899  INFO 8208 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$3047a3b6] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.5.RELEASE)

2019-08-19 01:11:20.348  INFO 8208 --- [           main] c.j.e.MasterEurekaServerApplication      : No active profile set, falling back to default profiles: default
2019-08-19 01:11:20.363  INFO 8208 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@3e44f2a5: startup date [Mon Aug 19 01:11:20 IST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@79e2c065
2019-08-19 01:11:22.110  INFO 8208 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=ea81071d-5482-367e-af9d-b21d3088ff2a
2019-08-19 01:11:22.145  INFO 8208 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-08-19 01:11:22.345  INFO 8208 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$3047a3b6] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-08-19 01:11:23.215  INFO 8208 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8761 (http)
2019-08-19 01:11:23.240  INFO 8208 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2019-08-19 01:11:23.240  INFO 8208 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.34

Response from the config-service is --->
"{"name":"Config-Serve","profiles":["default"],"label":null,"version":"96e6e24ea27d705bf8d243ac69ff46a0698e0ba6","state":null,"propertySources":[]}"
```
please if anything i ma doing wrong let me know..

**Comment by spencergibb** [comment] 2019-08-18 20:18
What versions and dependencies are you using?

**Comment by tamal2401** [comment] 2019-08-18 20:23
Below are the dependencies that i have provided and the spring boot version also..

<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>Finchley.SR1</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

**Comment by spencergibb** [comment] 2019-08-18 20:31
Starting a config server doesn't read from git. Only when a client reads from config server will you see anything.

Also, boot 2.0.x and Finchley are not supported anymore, I'd recommend upgrading to boot 2.1.x and Greenwich.SR2.

**Comment by tamal2401** [comment] 2019-08-19 18:59
but when i was trying to hit the below provided url it is returning a blank response but no error response.
URL : "http://localhost:8080/Config-Server/default"
this url supposed to get the config resources from the git ?

the response is coming as 
"{"name":"Config-Serve","profiles":["default"],"label":null,"version":"96e6e24ea27d705bf8d243ac69ff46a0698e0ba6","state":null,"propertySources":[]}"

There is no particular error is also there so i am confused...and i will try changing the spring boot version..thanks but if you have any other suggestion let me know please..

**Comment by tamal2401** [comment] 2019-08-19 19:15
I have also created a config client service and tried reading config from this service but still not able to get the config.
providing the bootstrap..

spring:
cloud:
config:
uri: http://localhost:8080
eureka:
client:
service-url:
default-zone: http://localhost:8761/eureka/
register-with-eureka: true
fetch-registry: true

**Comment by ryanjbaxter** [comment] 2019-08-19 23:44
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-09-02 23:48
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-09-02 23:48 UTC
Labels: feedback-reminder, waiting for feedback
