### ISSUE TITLE
How to configure a client with multiple configuration files simultaneously.

### ISSUE THREAD

**Issue by jdeegan** [spring-cloud/spring-cloud-config#1494] opened 2019-10-22 15:49 UTC
**Question**

We have a very simple application that displays a greeting message in a language. 

The language key value is specified in two property files, boot-1.properties and boot-2.properties. Our program is currently only pulling in the configuration from one file. 

**CURRENT PROPERTY FILES IN CONFIGURATION FOLDER**
boot-1.properties:
```
lang: en
list: Harry Potter
```

boot-2.properties: 
```
lang: fr
list: Scott Pilgrim
```

The following two configurations did not give us the result that we were looking for (We need both of these files to be read in together): 

A) 
bootstrap.properties:
```
spring.application.name=boot
spring.profiles.active=1,2
```

B)
bootstrap.properties: 
```
spring.application.name=boot
spring.cloud.config.name=boot-1, boot-2
```

Any help at all would be amazing!!

**Comment by spencergibb** [comment] 2019-10-22 15:58
`B` would be the one that works and it works for me.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-11-05 16:02
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-11-05 16:02 UTC
