### ISSUE TITLE
How to back the config server with a database?

### ISSUE THREAD

**Issue by joeweder** [spring-cloud/spring-cloud-config#236] opened 2015-09-22 16:21 UTC
Love the whole concept. But we believe we want to deploy the config server in the cloud and our chosen provider is SAP's Hand Cloud where there is no file system. I am thinking it would be ideal to back the server with a simple database. Consensus here seems to be we don't care about versioning. 

Google shows little on this and I was wondering if anyone has some helpful hints suggestions to get me started? Looking at a new DataSourceEnvironmentRepository I think?

**Comment by spencergibb** [comment] 2015-09-22 16:26
Closing as a duplicate of #203, please make any comments there.

**Closed by spencergibb** 2015-09-22 16:26 UTC
