### ISSUE TITLE
spring.config.import configuration clashes with spring.cloud.config.enabled

### ISSUE THREAD

**Issue by nucatus** [spring-cloud/spring-cloud-config#1877] opened 2021-05-11 15:40 UTC
## Observed behaviour

A `spring.config.import` config property is set to `optional:configserver:http://myconfigserver:5656` in a main configuration file `application.properties`. In the `application-dev.properties` config file, the property `spring.cloud.config.enabled` is set to false, since we don't require any property to be loaded from the remote config server on the dev profile. However, the observed behavior is that `ConfigServerConfigDataLoader` implementation doesn't take into account that setting and is going to try to pull that configuration from the remote server. If the connection fails, it will check for the `fail-fast` and `isOptional` flags and [make a decision](https://github.com/spring-cloud/spring-cloud-config/blob/be708efc18b2d503f9f27b3d96cbc668f938aaaa/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLoader.java#L177) based on that outcome.

## Intended behavior

If the `spring.cloud.config.enabled` property is set to `false`, `ConfigServerConfigDataLoader` should not even try to connect to the remote server and return as soon as possible.

**Comment by nucatus** [comment] 2021-05-12 03:43
Spring Cloud 2020.0.2

It's not an error that is thrown, only that the behavior is not the expected one. 

When I disable the cloud config client, I expect the config server not to be called at all, which is not the case.

**Comment by nucatus** [comment] 2021-05-12 05:06
I created a small project to demonstrate the issue. 

https://github.com/nucatus/spring-config-enabled-issue

**Comment by ryanjbaxter** [comment] 2021-05-12 13:49
the problem is that you have `spring.cloud.config.enabled` in a profile specific document.  My guess is that `spring.config.import` is processed before any properties from profiles are applied and so boot includes the config data loader from the config client.

if you move the property to application.properties, or use an environment variable, it works as expected.

@spencergibb @philwebb is this behavior intended?  Should we look at any profile specific configuration properties and apply those before fetching configuration?

**Comment by ryanjbaxter** [comment] 2021-05-12 14:41
The problem doesn't get worse IMO, that is the expected behavior.  Boot does not know what `configserver` is because you have removed disable spring cloud config and it has not config data loader to handle that protocol.

Lets take a step back...

Why disable spring cloud config in the first place?  With the `optional` syntax it will fail silently when the config server is not present.

**Comment by nucatus** [comment] 2021-05-12 16:08
Because that `optional` flag actually means that spring cloud config will try to connect to that server and will keep retrying until finally decides to step back. You will loose few good seconds there in the startup process, which in a development environment, it's quite a pain.

This is why we need a `dev` profile where we don't rely on that config loaded from the spring config remote server.

Moreover, what is then the purpose of having the ability to disable the client config if that is not working?! Basically, that flag becomes useless.

**Comment by spencergibb** [comment] 2021-05-12 16:27
all spring.config.import entries are evaluated. They do not behave like normal properties that can be overridden. Properties in a profile can not, by definition, influence an import in the default profile. If you don't want import in default, the only option is to not put an import there.

**Comment by nucatus** [comment] 2021-05-13 05:27
OK. This, indeed, is the path we should have thought of. The slightly change is that we have to enable the config client and provide the config server URL thgrough environment variables for the targeted profiles and have the client config disabled on the default configuration. This is the other way around compared to the old implementation where we had a spring config server set for the default profile and config client disabled for some particular profiles, like dev.

After reading the documentation again for the [`spring.config.import`](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-files-importing), it is clear that that import is evaluated before any profile specific configuration is applied. However, there is a bit of confusion that comes with the added complexity. Maybe, this is because the new mechanics about how configuration is loaded in Spring Boot 2.4.

**Comment by ryanjbaxter** [comment] 2021-05-13 14:11
@nucatus let us know if there is anything we can do to make things clearer.  I will close this for now.

**Closed by ryanjbaxter** 2021-05-13 14:11 UTC
Labels: feedback-provided

**Comment by mplain** [comment] 2021-09-07 13:04
Just spent two days trying to figure out why the dockerfile command line argument does not override spring.config.import specified in application.properties.
 
#spencergibb
all spring.config.import entries are evaluated. They do not behave like normal properties that can be overridden. 

this migration has been very painful =_=

**Comment by JassonLuiz** [comment] 2023-07-14 18:10
> o problema é que você tem `spring.cloud.config.enabled`em um documento específico do perfil. Meu palpite é que `spring.config.import`é processado antes que quaisquer propriedades dos perfis sejam aplicadas e, portanto, a inicialização inclui o carregador de dados de configuração do cliente de configuração.
> 
> se você mover a propriedade para application.properties ou usar uma variável de ambiente, ela funcionará conforme o esperado.
> 
> @spencergibb @philwebbesse comportamento é intencional? Devemos examinar as propriedades de configuração específicas do perfil e aplicá-las antes de buscar a configuração?

Hi Ryan, thank you very much. I was having problem with this, so I put the 'spring.config.import' first than any property and that solved it for me. I am using Spring 3.1.1

**Comment by htpaf** [comment] 2024-11-27 08:33
For others searching for solutions to this problem, 
have a look at https://github.com/awspring/spring-cloud-aws/issues/824 and the fix part https://github.com/awspring/spring-cloud-aws/pull/1009. 

In short the following is possible and may helpful if you want to disable secretsmanager and parameterstore during testing:
```yaml
# src/main/test/resources/application.properties
spring.cloud.aws.secretsmanager.enabled=false
spring.cloud.aws.parameterstore.enabled=false
```
The above assumes `src/main/resources/application.yml` is used (with multi-document support and profile activation -- though not necessary)

**Comment by htpaf** [comment] 2025-04-17 10:20
**UPDATE** (2025-04-17)

While upgrading from Spring Boot 3.3.7 to 3.4.4 this issue popped up again (related to [required property spring.cloud.aws.region](https://stackoverflow.com/questions/79378740/spring-boot-unable-to-load-region-error-despite-disabling-secrets-manager-in)  / https://stackoverflow.com/q/79378740)

Thanks to the information provided at  https://davidagood.com/disable-spring-cloud-aws/, it was possible to remove the `application.properties` file by using the following configuration in `application.yml`:
```
spring:
  autoconfigure:
    exclude: 
      - io.awspring.cloud.autoconfigure.config.parameterstore.ParameterStoreAutoConfiguration
      - io.awspring.cloud.autoconfigure.config.secretsmanager.SecretsManagerAutoConfiguration
```
for the appropriate profiles: 

```
spring:
  config:
    activate:
      on-profile: local-dev, local-test
```
There is a specific "unit" test that goes through all profiles to check their configuration parameters, and by using `@TestPropertySource` allowed disabling the import configurations so that the test would work. Here is the basic setup:

```
@SpringJUnitConfig(
        // load application.yml configuration.
        initializers = {ConfigDataApplicationContextInitializer.class},
        // only activate wanted onfiguration beans.
        classes = {DataSourceConfig.class}
)
// Run autoconfiguration as SpringBoot would do it (as of v3.4.4). 
// For shorter runtime -> https://docs.spring.io/spring-boot/appendix/test-auto-configuration/slices.html.
@ImportAutoConfiguration(classes = {DataSourceAutoConfiguration.class})
@TestPropertySource(properties = {
        "spring.cloud.aws.secretsmanager.enabled=false",
        "spring.cloud.aws.parameterstore.enabled=false"
})
abstract class DataSourceConfigTest {
  ...tests go here...
  @Autowired DataSource;
}
------------------------------------------
------------------------------------------

@Configuration
public class DataSourceConfig {

    @Bean
    @Primary
    @ConfigurationProperties("spring.datasource.rw")
    public DataSourceProperties rwDataSourceProperties() {
        return new DataSourceProperties();
    }
  ... more stuff here...

 }
```
Essentially, the `application.properties` file has been replaced by `@TestPropertySource`, which can override the secretsmanager and parameterstore in this test scenario.
