### ISSUE TITLE
Spring Cloud Config made a strange mistake

### ISSUE THREAD

**Issue by MrSix951223** [spring-cloud/spring-cloud-config#1086] opened 2018-07-13 08:44 UTC
The SpringBoot I use is version 2.0.1 and Spring Cloud  I use is version F. The Spring Cloud GateWay's process is not down, but its routing is not available, and Spring Cloud Config looks for its own branches, which are not in my configuration at all.This is when the routing address is called, and the response value is 500.

**Comment by MrSix951223** [comment] 2018-07-13 09:05
2018-07-10 21:48:43.003 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] Line:182 - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request proc
essing failed; nested exception is org.springframework.cloud.config.server.environment.NoSuchLabelException: No such label: pma] with root cause
org.eclipse.jgit.api.errors.RefNotFoundException: Ref pma can not be resolved


2018-07-10 21:48:31.203 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] Line:182 - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request proc
essing failed; nested exception is org.springframework.cloud.config.server.environment.NoSuchLabelException: No such label: scripts] with root cause
org.eclipse.jgit.api.errors.RefNotFoundException: Ref scripts can not be resolved



2018-07-10 21:46:41.108 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] Line:182 - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request proc
essing failed; nested exception is org.springframework.cloud.config.server.environment.NoSuchLabelException: No such label: com_joommyadmin] with root cause
org.eclipse.jgit.api.errors.RefNotFoundException: Ref com_joommyadmin can not be resolved

**Comment by ryanjbaxter** [comment] 2018-07-13 13:56
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

I really dont understand the problem you are experiencing.  Could you provide a sample that reproduces the issue along with steps how to reproduce it?

**Comment by marcingrzejszczak** [comment] 2018-07-13 20:46
Ping @MrSix951223 ?

**Comment by MrSix951223** [comment] 2018-07-13 23:39
The Spring Cloud GateWay configured a simple routing rule.Its configuration was taken from Spring Cloud Config using GitLab.However, it was previously configured with a usable routing address and suddenly could not be accessed.I logged in to the centos7 server and found that its process had not been killed, and it was still registered in eureka, but accessing the configured routing address would result in the above error.

**Comment by spencergibb** [comment] 2018-07-14 00:04
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spencergibb** [comment] 2019-02-11 15:20
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2019-02-11 15:20 UTC
Labels: feedback-provided

**Comment by TheSeaYouAreAllWater** [comment] 2020-03-12 08:53
> The Spring Cloud GateWay configured a simple routing rule.Its configuration was taken from Spring Cloud Config using GitLab.However, it was previously configured with a usable routing address and suddenly could not be accessed.I logged in to the centos7 server and found that its process had not been killed, and it was still registered in eureka, but accessing the configured routing address would result in the above error.

l also search question,How did you solve it?
