### ISSUE TITLE
After /actuator/busenv call to /actuator/busrefresh is required, also reset is impossible

### ISSUE THREAD

**Issue by 12ozCode** [spring-cloud/spring-cloud-config#2204] opened 2023-01-04 20:41 UTC
[Documentation ](https://docs.spring.io/spring-cloud-bus/docs/current/reference/html/) doesn't mention that after calling `/actuator/busenv` we must to call `/actuator/busrefresh` to apply changes on instances.

Also is there a way to reset such changes?
For example, I override some property on all instances for a moment using `/actuator/busenv + /actuator/busrefresh`.
Then I change the value in Spring Cloud Config DB, and want all services to redownload config from db, as they do on startup from Config Server, and forget overridden value provided by `/actuator/busenv`. 
But now it is impossible, call to /actuator/busrefresh won't help. 
And I can't force them to redownload config as they do on startup.

**Comment by ryanjbaxter** [comment] 2023-01-04 20:46
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment] 2023-01-11 20:51
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2023-01-18 20:51
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2023-01-18 20:51 UTC
Labels: waiting for feedback, feedback-reminder
