### ISSUE TITLE
Spring cloud config server on refresh -> the log display is incorrect, show  like application_name_IS_UNDEFINED

### ISSUE THREAD

**Issue by FUCKU** [spring-cloud/spring-cloud-config#2068] opened 2022-03-24 05:58 UTC
The other microservices start normally, and the log gets the spring.application.name correctly, However, when the refresh
endpoint is called, the log does not get the correct spring.application.name after the configuration is updated.
the log shows that XXX IS UNDEFINED.

To be exact, anything like <springProperty scope="context" ....../> does not get the value correctly.

Is this a bug? Or is a New Feature I need ? Or what exactly am I going to do?
I tried several schemes, including changing the logback-spring.xml file to something else and loading it in the application.yml file, but nothing worked.
Versions:
<spring-boot.version>2.5.10</spring-boot.version>
<spring-cloud.version>2020.0.5</spring-cloud.version>

 a Minimal, Reproducible Example : https://github.com/FUCKU/cloudSampleProjects

**Comment by ryanjbaxter** [comment] 2022-03-24 18:59
Please simplify the sample so its the minimal thats needed to reproduce the problem.  Also could you please upgrade to 2021.0.1

**Comment by spring-cloud-issues** [comment] 2022-03-31 18:59
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-04-07 18:59
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-04-07 18:59 UTC
Labels: waiting for feedback, feedback-reminder
