### ISSUE TITLE
Auto-refresh doesn't work when profile-specific file is updated in the Git repo

### ISSUE THREAD

**Issue by ChiragMoradiya** [spring-cloud/spring-cloud-config#1884] opened 2021-05-23 08:02 UTC
**Describe the issue**
- Given `application-couchdb.yml` file exists in the git repository
- And a config-server is configured to use this git repository.
- And a service (config-client) is running with the profile `couchdb`.
- And config-server & service (config-client) both have enabled cloud-bus.
- And Gitlab webhook is configured to notify to the config-server when there is any change in the git repo
- When I update `application-couchdb.yml` and push into git repo
- Then the service doesn't refresh its configuration. (ISSUE)
- But, If I update the `application.yml` and push into the git repo
- Then the service configuration is updated successfully. This concludes that the cloud-bus configuration/setup is working ok.

**Expected result**
When I update `application-couchdb.yml` and push into git repo; Then the service should refresh it's configuration

**Sample**
Sorry! I am not providing a sample for now. Let me know if it's required.

**Cause**
I tried to debug the issue; and found that the `RemoteRefreshApplicationEvent.destination` isn't set properly in this case. It sends a notification for this git change on destination = `*:couchb` (more precisely `*:couchdb:**`).
As `spring.cloud.bus.id` of the service (config-client) is `service1:80:f2a50a0b35cf65a764eec93d51431693` it doesn't match with the destination described in the event.

**Suggested Fix**
[`PropertyPathEndpoint.guessServiceName`](https://github.com/spring-cloud/spring-cloud-config/blob/be708efc18b2d503f9f27b3d96cbc668f938aaaa/spring-cloud-config-monitor/src/main/java/org/springframework/cloud/config/monitor/PropertyPathEndpoint.java#L105) should be updated. It shouldn't use `profile` in the serviceName. So, In this case the serviceName built by it should be `*` instead of `*:couchdb`. 

In another scenario where `user-couchdb.yml` was changed, ServiceName should be `user` instead of `user:couchdb`.

**Comment by spencergibb** [comment] 2021-06-03 18:57
Maybe add an option to not include the profile.

**Comment by ThomasVitale** [comment] 2021-12-21 16:41
I experienced the same issue. Currently, as a workaround, I considered setting `spring.cloud.bus.id=${spring.application.name}:${spring.profiles.active}` in case only one profile is active. If more profiles are enabled, it won't work.

I'm available to help fix this issue.

**Comment by ryanjbaxter** [comment] 2022-09-13 12:37
Duplicate of #2120 2138

**Closed by ryanjbaxter** 2022-09-13 12:37 UTC
Labels: enhancement, help wanted
