### ISSUE TITLE
Configurations are not combined as expected

### ISSUE THREAD

**Issue by Manny404** [spring-cloud/spring-cloud-config#1404] opened 2019-06-07 07:50 UTC
We have 2 Microservies one is called Applications the other Location. If I now create an application-dev.yml and an applications-dev.yml the Applications Service gets only the content of the applications-dev.yml. The Location Service gets the data from its location-dev.yml and the application-dev.yml. 

My expectation is that the Applications Service gets the values from both files like the Location Service.

This behavior occurs when configuring from files as well as from a GIT repository.

Using Jhipster Registry 4.1.1/5.0.0 contains  Spring Boot 2.1.4-RELEASE

[central-config.zip](https://github.com/spring-cloud/spring-cloud-config/files/3264917/central-config.zip)

**Comment by ryanjbaxter** [comment] 2019-06-10 14:33
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.  Also please remove the JHipster dependencies in your sample so you are only using Spring Cloud.

**Comment by Manny404** [comment] 2019-06-11 09:14
Simple Cloudconfig Server as possible: https://github.com/Manny404/demoCloudConfig

The Config files are in the https://github.com/Manny404/demoConfigFiles repo. 
Start the ConfigServer and get the following configurations:
http://localhost:8888/application/dev result in "basicconf":"basic"

http://localhost:8888/application**s**/dev results in "test":"test"   basic config ist missing

http://localhost:8888/location/dev results in "basicconf":"basic" AND "test":"location"

My expectation is that the basic config and the config from the applications file will also come back when I retrieve applications. As for the locationservice

I omitted a client implementation because the problem is already visible in the browser.

**Comment by spencergibb** [comment] 2019-06-17 14:29
There may be an edge case, but naming something `applications` as an application name is wonky.

**Comment by ryanjbaxter** [comment] 2019-06-17 14:29
If you rename `applications` to something else does it work as expected?

**Comment by Manny404** [comment] 2019-06-24 08:33
Ja mit den location Service tritt das Problem nicht auf. Ich habe auch noch 8 andere Services die das Problem nicht haben, die ich aber der Übersicht wegen weggelassen habe.

**Comment by ryanjbaxter** [comment] 2019-06-24 15:33
Sorry could you translate that to English please?

**Comment by Manny404** [comment] 2019-06-24 15:54
Yes, with the location service the problem does not occur. I also have 8 other services that don't have the problem, but I omitted them for the sake of clarity.

**Comment by ryanjbaxter** [comment] 2019-06-25 19:41
So it sounds like naming an application `applications` is not acceptable.  Our suggestion then is to rename the application to something else.

**Comment by spring-issuemaster** [comment] 2019-07-02 19:42
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-07-09 19:42
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-07-09 19:42 UTC
Labels: feedback-reminder, waiting for feedback
