### ISSUE TITLE
Spring Cloud Config client not able to connect to the Spring Cloud Config server

### ISSUE THREAD

**Issue by krisjha** [spring-cloud/spring-cloud-config#2404] opened 2024-04-11 09:58 UTC
**Describe the bug**
We are using  spring-cloud-starter-config version 4.1.0 and spring-cloud-config-client  version 4.1.0 . 

Both our config server and config client microservice are running as pod in OpenShift environment. We don't
have any issue when we are running one replica of config client, config client is successfully calling the config server rest api and getting the configuration parameter. 

Problem starts when we are increasing the number of replica to 2 and starting both pod concurrently, in this case one of the pod gets the configuration from config server and other  one fails and I find the below error message 

main] o.s.c.c.c.ConfigServerConfigDataLoader   : Fetching config from server at : http://config-svc:7002/api/v1/ss/config/getServiceConfig
2024-04-04T00:17:11.240Z  INFO 1 --- [projectmgr-svc] [           main] o.s.c.c.c.ConfigServerConfigDataLoader   : Exception on Url - http://config-svc:7002/api/v1/ss/config/getServiceConfig:org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://config-svc:7002/api/v1/ss/config/getServiceConfig/projectmgr-svc/DEV/1.0": config-svc. Will be trying the next url if available

We are using the service name of config server as both client and server are there in the same namespace.

Please let us know the corrective action which we should be taking to resolve this issue. Any help is much appreciated

**Comment by krisjha** [comment] 2024-04-12 10:14
Retry has solved the issue. But I fail to understand why at fort go it is failing when the other is getting connected successfully.

**Comment by ryanjbaxter** [comment] 2024-04-12 13:09
I am wondering if this is some kind of issue with K8S, can you reproduce the issue outside of K8S?

**Comment by spring-cloud-issues** [comment] 2024-04-19 13:14
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2024-04-26 13:14
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2024-04-26 13:14 UTC
Labels: feedback-reminder
