### ISSUE TITLE
Removal of Zuul route not respected in ZuulProperties

### ISSUE THREAD

**Issue by JWThewes** [spring-cloud/spring-cloud-config#643] opened 2017-02-16 07:50 UTC
I'm not sure if this is correct in the Config subproject but for me this fits best.

We have the following setup:
Cameden SR5
One ConfigServer
One Zuul
One RabbitMQ

When we're remove one route from the Config of the ZuulServer and invoke the /monitor event the removed Route is still present on the ZuulProperties on the ConfigClient (Zuul).
The ConfigServer serves the correct configuration (Route is removed) but on the client itself the ZuulProperties still have this route.

If you need any further information feel free to ask anytime.

**Comment by spencergibb** [comment] 2017-02-16 16:00
Duplicate of https://github.com/spring-cloud/spring-cloud-netflix/issues/705

**Closed by spencergibb** 2017-02-16 16:00 UTC
