### ISSUE TITLE
can't initialize database schema when Spring Cloud Config is in the classpath.

### ISSUE THREAD

**Issue by creactiviti** [spring-cloud/spring-cloud-config#983] opened 2018-04-19 14:21 UTC
Spring Cloud Version: Finchley.M9
Java Version: 8

Dependency:

```
   <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-config</artifactId>
     <version>2.0.0.M9</version>
  </dependency>
```

Startup config:

```
-Dspring.datasource.initialization-mode=always
```

Console:

```
The dependencies of some of the beans in the application context form a cycle:

   servletEndpointRegistrar defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration.class]
      ↓
   healthEndpoint defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]
      ↓
   dbHealthIndicator defined in class path resource [org/springframework/boot/actuate/autoconfigure/jdbc/DataSourceHealthIndicatorAutoConfiguration.class]
┌─────┐
|  scopedTarget.dataSource defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]
↑     ↓
|  org.springframework.boot.autoconfigure.jdbc.DataSourceInitializerInvoker
└─────┘
```

When I remove the Spring Cloud Config dependency everything works just fine.

**Comment by ryanjbaxter** [comment] 2018-04-19 21:11
Seems like this might be a duplicate of https://github.com/spring-cloud/spring-cloud-commons/issues/355.  Could perhaps supply a sample in that issue?

**Closed by ryanjbaxter** 2018-04-19 21:11 UTC
Labels: duplicate
