### ISSUE TITLE
eureka and config  Asynchrony

### ISSUE THREAD

**Issue by ChenZheOnePiece** [spring-cloud/spring-cloud-config#1570] opened 2020-03-10 10:48 UTC
this is eureka 
![image](https://user-images.githubusercontent.com/25056180/76305077-6f32bc80-62ff-11ea-9d45-e81d846274d2.png)

this is admin 
![image](https://user-images.githubusercontent.com/25056180/76305112-807bc900-62ff-11ea-893b-4eb1ca0470c0.png)

amdin with eureka  Asynchrony beacuse  config
I mentioned that before. You said it would be fixed in SR3
Did I do something wrong

**Comment by spencergibb** [comment] 2020-03-10 10:55
A couple of screenshots don't describe a problem. Please describe in detail what the problem is.

**Comment by spring-issuemaster** [comment] 2020-03-17 10:58
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-03-24 10:58
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-03-24 10:59 UTC
Labels: feedback-reminder, waiting for feedback
