### ISSUE TITLE
I am trying to get Spring cloud config running. The documents are out of date and now quite confusing

### ISSUE THREAD

**Issue by AnthonyCavanagh** [spring-cloud/spring-cloud-config#2014] opened 2021-12-16 01:20 UTC
What I am trying to do is to connect to a remote git repository on BitBucket, But I keep getting an exception 
2021-12-16 01:04:20.856  INFO 5728 --- [nio-8888-exec-1] .c.s.e.MultipleJGitEnvironmentRepository : Will try to checkout master label instead.
2021-12-16 01:04:22.276  WARN 5728 --- [nio-8888-exec-1] .c.s.e.MultipleJGitEnvironmentRepository : Error occured cloning to base directory.
org.eclipse.jgit.api.errors.TransportException: git@bitbucket.org:tcavanagh/hp-fetcher-configurations.git: failed to send channel request
[Exceptions.txt](https://github.com/spring-cloud/spring-cloud-config/files/7723866/Exceptions.txt)

It wont tell me why it cant clone to base directory, or even where base directory is.  I have an application yml which contains all the details I have set up. It includes a private key, but that is ok I will regenerate a new one.
[application.yml.txt](https://github.com/spring-cloud/spring-cloud-config/files/7723857/application.yml.txt)

And the exceptions,
[Exceptions.txt](https://github.com/spring-cloud/spring-cloud-config/files/7723867/Exceptions.txt)

The error may be in how I am calling it. I am  http://localhost:8888/application/default  application being the name of the application.yml file.

**Comment by ryanjbaxter** [comment] 2021-12-16 01:28
Is this not the same as https://github.com/spring-cloud/spring-cloud-config/issues/2013?

**Comment by AnthonyCavanagh** [comment] 2021-12-16 02:26
2013? was to complicated a ticket, This is more neater.

**Comment by healthy-interac** [comment] 2021-12-17 23:45
Hey @ryanjbaxter , I'm getting similar exception now, when trying to upgrade from Spring Cloud 2020.0.4 to 2021.0.0.
I'm using git SSH configuration using properties, repo is hosted on bitbucket.
When running with 2020.0.4 everything works fine, no exceptions, config server starts as expected. We use this config server app for a while.
After changing version to 2021.0.0 and starting the app, I've realized different behaviour re ssh: somehow this line is printed now, requiring to enter passphrase:

Enter passphrase for /Users/<my-user>/.ssh/<myuser>-Bitbucket:

After entering valid password , or just pressing Enter following exception is thrown and app is aborting:

2021-12-17 17:59:18.308  WARN 18400 --- [           main] .c.s.e.MultipleJGitEnvironmentRepository : Error occured cloning to base directory.

org.eclipse.jgit.api.errors.TransportException: git@bitbucket.org:<my-repo-name>.git: failed to send channel request
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:224)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:303)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:178)
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.cloneToBasedir(JGitEnvironmentRepository.java:658)
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.initClonedRepository(JGitEnvironmentRepository.java:363)
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.afterPropertiesSet(JGitEnvironmentRepository.java:284)
	at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.afterPropertiesSet(MultipleJGitEnvironmentRepository.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290)
	at com.healthyinteractions.configserver.ConfigServerApplication.main(ConfigServerApplication.java:12)
Caused by: org.eclipse.jgit.errors.TransportException: git@bitbucket.org:healthyinteractions/m4h-config.git: failed to send channel request
	at org.eclipse.jgit.transport.JschSession$JschProcess.<init>(JschSession.java:167)
	at org.eclipse.jgit.transport.JschSession.exec(JschSession.java:77)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:289)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:153)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:142)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:94)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1309)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:213)
	... 24 common frames omitted
Caused by: com.jcraft.jsch.JSchException: failed to send channel request
	at com.jcraft.jsch.Request.write(Request.java:65)
	at com.jcraft.jsch.RequestEnv.request(RequestEnv.java:52)
	at com.jcraft.jsch.ChannelSession.sendRequests(ChannelSession.java:222)
	at com.jcraft.jsch.ChannelExec.start(ChannelExec.java:41)
	at com.jcraft.jsch.Channel.connect(Channel.java:152)
	at org.eclipse.jgit.transport.JschSession$JschProcess.<init>(JschSession.java:159)
	... 31 common frames omitted

**Comment by vlagorce** [comment] 2022-01-26 15:29
Facing same issue after upgrading 
from spring-boot-starter-parent 2.5.3 to spring-boot-starter-parent 2.6.3
from spring-cloud-dependencies 2020.0.5 to spring-cloud-dependencies 2021.0.0

jgit upgrade from 5.1.3.201810200350-r  to 5.12.0.202106070339-r might be the cause.

**Comment by bogoevskig** [comment] 2022-01-26 17:13
Got the same error in Spring Cloud Config 3.1.0 (Spring Cloud 2021.0.0). Looks like it is related to the git protocol version switch from V1 to V2 in JGit since version 5.11

Switching the git protocol version back to V1 on client side resolved the issue. You can do it by adding the following lines in the JGit configuration file ($HOME/.config/jgit)

```
[protocol]
    version = 1
```

or you can update global git protocol version with

`git config --global protocol.version 1`

**Comment by vlagorce** [comment] 2022-01-27 09:24
> `git config --global protocol.version 1`
Is the same as
 ($HOME/.gitconfig)
 [protocol]
    version = 1

**Comment by vlagorce** [comment] 2022-01-27 12:20
I still have the "Will try to checkout master label instead." Despite using "SPRING_CLOUD_CONFIG_LABEL" = "master"

**Comment by Bryksin** [comment] 2022-02-11 10:58
The same problem, I just upgraded the config service to the latest Spring Boot and suddenly default label become "main" instead fo "master" and it stop checking out code without even telling why.

Just getting Warning message: `.c.s.e.MultipleJGitEnvironmentRepository : Could not fetch remote for master remote <my_repo_url>`
With a bit of debugging and intercepting internal exception I found this:

`org.eclipse.jgit.errors.TransportException: <my_repo_url>: failed to send channel request` which is also not very informative

Configuring `git config --global protocol.version 1` considering service runs in docker in EKS doesn't feel right as docker at os level doesn't even have git installed and fully rely on Config Service libs

Is there a way to set this protocol version from the `application.yml` file?

**Comment by rkusumoto** [comment] 2022-04-11 22:02
Attempting to set in application.yml: spring.cloud.config.server.git.defaultLabel or default-label to master does not seem to work.  It's always going to main then master (and since I don't have a main branch, gettings a lot of java logs).

Using Spring Cloud Config in a container.

**Comment by ryanjbaxter** [comment] 2022-04-12 00:36
`spring.cloud.config.server.git.defaultLabel` should work, but that is a different issue.

**Comment by Incarnation-p-lee** [comment] 2022-04-27 02:49
Is there any update about this regression? Set `git config --global protocol.version 1` can workaround this from myside.

**Comment by ryanjbaxter** [comment] 2022-04-27 20:19
We ultimately will need a way to set the protocol via a jgit api and thus far I have yet to find such an api.  As far as I can see the only way to do it is by setting the git config

**Comment by Incarnation-p-lee** [comment] 2022-04-28 07:17
I see, thank you!

**Comment by ryanjbaxter** [comment] 2022-04-28 13:18
Duplicate of https://github.com/spring-cloud/spring-cloud-config/issues/2015

**Closed by ryanjbaxter** 2022-04-28 13:18 UTC
Labels: feedback-provided
