### ISSUE TITLE
password encrypted with jasypt is breaking when "refreshed" using actuator/bus-refresh

### ISSUE THREAD

**Issue by krishna2025** [spring-cloud/spring-cloud-config#1567] opened 2020-03-06 11:57 UTC
Hi tannaga ,
@tannaga
https://github.com/spring-cloud/spring-cloud-config/issues/808#issuecomment-334249042

@spencergibb @ryanjbaxter @jnulwliang  @sathish593
I am facing similar issue, I followed the procedure mentioned.
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false  (so that configserver will not encript).

Created 
org.springframework.cloud.bootstrap.BootstrapConfiguration=com.ulisesbocchio.jasyptspringboot.JasyptSpringBootAutoConfiguration  under META-INF/spring.factories under resource folder , but still I am facing issue, I am reading property from gitlab" the encripted pwd with ENC(xx)" at application.yml , during configServer starup and application startup I am able to see decripted pwd properly, If I change a property in applicatio.yml and hit actuator/bus-refresh  "the  decripted pwd is populating as change ex: o.s.cloud.bus.event.RefreshListener - Received remote refresh request. Keys refreshed [password] " but I did not change anything on this property. Can some one help on this?

**Comment by ryanjbaxter** [comment] 2020-03-09 14:41
If you can provide a sample and a better description of the problem we would be happy to help.

Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by krishna2025** [comment] 2020-03-10 12:02
Hi 
@ryanjbaxter 
Thx for quick reply. 

db2:
  datasource:
    jdbc-url: jdbc:db2://hostname:port/database:currentSchema=default    
   username: 
    password: ENC(cppertuvnh)
    driverClassName: com.ibm.db2.jcc.DB2Driver
     schema: default 
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      #minimum-idle: 2
      #idle-timeout: 10000
      pool-name: HikariConnectionPool
      pool-prepared-statements: true

I am maintaining these properties at application-dev1.yml file in Git 
When I start config-client, it is able to get properties from git and decript the password: ENC(cppertuvnh) properly.
Issue is:
If I change connection-timeout to 50000 and trigger 
https://hostName/dev1/actuator/bus-refresh/CspringAppName
I am getting this message Received remote refresh request. Keys refreshed [connection-timeout, password].Due to this my password is chnaged to  ENC(cppertuvnh) and databased conenctin are failing. Need help on this how to fix it.

**Comment by krishna2025** [comment] 2020-03-11 06:03
@ramkumarar
 I'm using jasypt-spring-boot-starter (2.1.0) in a spring cloud config project.When the config loads for the firt time from config server the encrypted values are getting properly decrypted. But when i do a refresh via actuator endpoint the encrypted value is passed as is and not getting decrypted. Iam having following properties in cloud configuration and passing the password via JVM run time argument -Djasypt.encryptor.password=pass

app.enc.attribute = ENC(hKF3c7lizZKAi75e9q9JCQ==)
jasypt.encryptor.bootstrap = true
jasypt.encryptor.algorithm = PBEWITHMD5ANDTRIPLEDES


I see in your post https://github.com/ulisesbocchio/jasypt-spring-boot/issues/112
above issue was resloved, can u please help how did u do that ? Step by step process

**Comment by ryanjbaxter** [comment] 2020-03-11 21:16
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by spring-issuemaster** [comment] 2020-03-18 21:18
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-03-25 21:18
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-03-25 21:18 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by haovu429** [comment] 2023-04-27 18:23
ok
