### ISSUE TITLE
server.port property is not worked when combing Spring Cloud Config with other Spring projects.

### ISSUE THREAD

**Issue by 5teven-tian** [spring-cloud/spring-cloud-config#1396] opened 2019-05-24 02:25 UTC
Bug report

As title . Following is its reproduce step:
1. set 
server:
  port: 8202 
in application.yml

2. together with below dependencies , tomcat start at port 8082 
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
                        <version> 2.1.0.RELEASE</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
                        <version> 2.1.0.RELEASE</version>
		</dependency>

I have tried to config server port programmatically when starting applications, 
or run with -Dserver.port=8202. Both of them are not worked.

But when I take rid of the starter-config dependency , server will start at port 8202.

Could anyone have a suggestion ?

Sincerely Regards.

**Comment by spencergibb** [comment] 2019-05-24 02:35
Doesn't make much sense to me unless you are fetching config that has some other server.port configured.

**Comment by 5teven-tian** [comment] 2019-05-24 02:46
> Doesn't make much sense to me unless you are fetching config that has some other server.port configured.

I am sure that only one place has this configuration. 
Following is its log :
2019-05-24 10:14:10.045  INFO 26532 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8082 (http)

May TomcatWebServer ignore the user defined value ? I have no idea about the sequence that  TomcatWebServer  read from.

**Comment by spencergibb** [comment] 2019-05-24 02:51
What does /actuator/env say?

**Comment by 5teven-tian** [comment] 2019-05-24 02:58
> What does /actuator/env say?

As it prints out much information , I just cut part of them about 8082.

{"activeProfiles":["development"],"propertySources":[{"name":"server.ports","properties":{"local.server.port":{"value":8082}}},
"server.port":{"value":"8082"}
{"value":"/tmp/tomcat.7165274625889880626.8082"},

**Comment by spencergibb** [comment] 2019-05-24 03:04
I don't understand. Is that from when it's working or not working?

**Comment by 5teven-tian** [comment] 2019-05-24 03:11
> I don't understand. Is that from when it's working or not working?

It is from not working.

I uploaded my config client project may benefit clarifying this issue.

[config-client.zip](https://github.com/spring-cloud/spring-cloud-config/files/3214905/config-client.zip)

**Comment by spencergibb** [comment] 2019-05-24 03:16
Is Dev tools setting it? I can't look at the project right now

**Comment by 5teven-tian** [comment] 2019-05-24 03:22
> Is Dev tools setting it? I can't look at the project right now

I use Eclipse to import config-client as Maven project .

**Comment by 5teven-tian** [comment] 2019-05-24 06:48
Following is my bootstrap.properties, the port setting is not be read.
But others is properly read.

server.port= 8202
spring.application.name = config-client
spring.profiles.active=development
spring.cloud.config.uri = http://10.4.3.76:8888
management.endpoints.web.exposure.include=*

**Comment by ryanjbaxter** [comment] 2019-06-03 15:57
It hard to try your sample since it is missing the config server piece.  I don't see anything there that would cause it not to work.

**Comment by 5teven-tian** [comment] 2019-06-03 23:04
> It hard to try your sample since it is missing the config server piece. I don't see anything there that would cause it not to work.

Because server piece works properly, so I didn't post it.

The problem I meet is "server.port" setting in bootstrap.properties is not recognized by embedded Tomcat server in client side. However , when I write "server.port" setting in application.yml . Tomcat server can recognize it . If I do so , another issue is the setting of Spring Cloud Config not worked in application.yml

**Comment by ryanjbaxter** [comment] 2019-06-03 23:37
Again we need a complete working sample to reproduce the problem.

**Comment by 5teven-tian** [comment] 2019-06-04 01:32
> Again we need a complete working sample to reproduce the problem.

Following is my code.


Client side start 
===================================================
ConfigClientApplication.java
`package com.example.configclient;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


@SpringBootApplication
public class ConfigClientApplication {
	
	public static void main(String[] args) {
		SpringApplication.run(ConfigClientApplication.class, args);
	}


}
`
Controller.java
`package com.example.configclient.controller;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RefreshScope
public class Controller {
	@Value("${welcome.message: default value}")
	String welcomeText;

	@RequestMapping(value = "/")
	public String welcomeText() {
		return welcomeText;
	}
}
`

bootstrap.properties
`server.port= 8202
spring.application.name = config-client
spring.profiles.active=development
spring.cloud.config.uri = http://10.4.3.76:8888
management.endpoints.web.exposure.include=*
`
pom.xml
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.5.RELEASE</version>
		<relativePath /> 
	</parent>
	<groupId>com.example</groupId>
	<artifactId>config-client</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>config-client</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
		<skipTest>true</skipTest>
	</properties>

	<dependencies>
	<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
			<version>2.1.2.RELEASE</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
	
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M3</version>
				<configuration>
					<skipTests>true</skipTests>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
`
=========================================
Client side end.

Server side start
============================================
ConfigserverApplication .java
`package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.config.server.EnableConfigServer;

@SpringBootApplication
@EnableConfigServer
public class ConfigserverApplication {
	public static void main(String[] args) {
		SpringApplication.run(ConfigserverApplication.class, args);
	}
}`

bootstrap.properties
`server.port = 8888
spring.profiles.active=native
#for windows
spring.cloud.config.server.native.searchLocations=file:///D:/temp
#for linux
#spring.cloud.config.server.native.searchLocations=/home/steven/temp
`
pom.xml
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.5.RELEASE</version>
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>config-server</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
			<version>2.0.4.RELEASE</version>
		</dependency>


	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
`
config-client-development.properties
`welcome.message = my test message 4
`

**Comment by spencergibb** [comment] 2019-06-04 01:33
A complete sample we can run as a zip file or a repo we can close, not pasted in comments.

**Comment by 5teven-tian** [comment] 2019-06-04 01:38
> A complete sample we can run as a zip file or a repo we can close, not pasted in comments.

Attached files are server & client project zip. Only source code , no IDE tool settings or binary files.


[config-client.zip](https://github.com/spring-cloud/spring-cloud-config/files/3250095/config-client.zip)
[config-server.zip](https://github.com/spring-cloud/spring-cloud-config/files/3250096/config-server.zip)

**Comment by ryanjbaxter** [comment] 2019-06-05 00:17
I cannot run these samples because they assume you are running on windows

**Comment by 5teven-tian** [comment] 2019-06-05 01:06
> I cannot run these samples because they assume you are running on windows

Following is for Linux , 

server.port = 8888
spring.profiles.active=native
spring.cloud.config.server.native.searchLocations=/home/temp

**Comment by spencergibb** [comment] 2019-06-05 20:40
When I run your samples I get the following for config client:
```
2019-06-05 16:38:16.161  INFO 30263 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8202 (http)
```

Looks like it is running fine on port 8202 from bootstrap.properties

**Comment by spring-issuemaster** [comment] 2019-06-12 20:41
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-19 20:42
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-06-19 20:42 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by pabloalencar** [comment] 2023-04-21 20:52
I had a similar problem. Cause: I configured SERVER_PORT environment variable, so no matter what you do at "server.port" in application.properties.
Solution: remove environment variable (from OS) or set to the port you want.

Reference: [https://docs.spring.io/spring-boot/docs/2.1.9.RELEASE/reference/html/howto-embedded-web-servers.html](url)

Hope this can help.
