### ISSUE TITLE
Could not locate configserver via discovery springCloudVersion 2021.0.4

### ISSUE THREAD

**Issue by zorlac** [spring-cloud/spring-cloud-config#2184] opened 2022-11-07 19:22 UTC
**Application uses:**  
Spring Parent: 2.7.5, Spring Cloud Version: 2021.0.4, Java Version: 11

**application.yml**  

    spring:  
      config:  
        import: optional:configserver:${CONFIG_SERVER:https://config-server}  
      cloud:  
        service-registry:  
          auto-registration:  
            enabled: ${app.enabled_discovery}  
        config:  
          label: ${CONFIG_BRANCH:${info.application.name}_Config}  
          discovery:  
            enabled: true  
            serviceId: config-server  

Everything is working fine  with **springCloudVersion 2021.0.3** and previous version. Did not change anything except the spring cloud version and when I ran I am getting this error:  

> Msg: **Could not locate configserver via discovery java.lang.IllegalStateException: No**
> **instances found of configserver (config-server)** 	at
> org.springframework.cloud.config.client.ConfigServerInstanceProvider.getConfigServerInstances(ConfigServerInstanceProvider.java:59)
> 	at
> org.springframework.cloud.config.client.ConfigServerInstanceMonitor.refresh(ConfigServerInstanceMonitor.java:90)
> 	at
> org.springframework.cloud.config.client.ConfigServerConfigDataLocationResolver.lambda$resolveProfileSpecific$8(ConfigServerConfigDataLocationResolver.java:228)
> 	at
> org.springframework.boot.DefaultBootstrapContext.getInstance(DefaultBootstrapContext.java:119)
> 	at
> org.springframework.boot.DefaultBootstrapContext.getOrElseThrow(DefaultBootstrapContext.java:111)
> 	at
> org.springframework.boot.DefaultBootstrapContext.get(DefaultBootstrapContext.java:88)
> 	at
> org.springframework.cloud.config.client.ConfigServerConfigDataLoader.load(ConfigServerConfigDataLoader.java:85)
> 	at
> org.springframework.cloud.config.client.ConfigServerConfigDataLoader.load(ConfigServerConfigDataLoader.java:61)
> 	at
> org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:107)
> 	at
> org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:128)
> 	at
> org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:86)
> 	at
> org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:116)
> 	at
> org.springframework.boot.context.config.ConfigDataEnvironment.processWithProfiles(ConfigDataEnvironment.java:311)
> 	at
> org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:232)
> 	at
> org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
> 	at
> org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
> 	at
> org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:102)
> 	at
> org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87)
> 	at
> org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
> 	at
> org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
> 	at
> org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
> 	at
> org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
> 	at
> org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
> 	at
> org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) 	at
> org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
> 	at
> org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
> 	at
> org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
> 	at
> org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:344)
> 	at
> org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
> 	at
> org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
> 	at
> org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)

**Comment by ryanjbaxter** [comment] 2022-11-07 19:38
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by ryanjbaxter** [comment] 2022-11-07 22:22
Yes the simplest app(s) needed to reproduce the problem

**Comment by spring-cloud-issues** [comment] 2022-11-14 22:26
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-11-21 22:26
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-11-21 22:26 UTC
Labels: waiting for feedback, feedback-reminder
