### ISSUE TITLE
Spring Config Server failed to start up with git conflict error

### ISSUE THREAD

**Issue by vishalmanohar** [spring-cloud/spring-cloud-config#407] opened 2016-05-24 04:10 UTC
We have been using Spring Cloud Config [1.0.2.RELEASE] for some time now and its working out well for us. Thank you!

Today, we noticed an error during the start up of the config server with the following stack trace:
Restarting the config server resolved the issue -- but was curious to know how this could have happened. 
Multiple apps rely on the same config server to start up and was wondering if it could be due to some concurrency issue.

<pre>
Caused by: org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
application.properties
....
....
    at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:265) ~[org.eclipse.jgit-3.5.3.201412180710-r.jar!/:3.5.3.201412180710-r]
    at org.springframework.cloud.config.server.JGitEnvironmentRepository.checkout(JGitEnvironmentRepository.java:129) ~[spring-cloud-config-server-1.0.1.RELEASE.jar!/:1.0.1.RELEASE]
    at org.springframework.cloud.config.server.JGitEnvironmentRepository.loadEnvironment(JGitEnvironmentRepository.java:110) ~[spring-cloud-config-server-1.0.1.RELEASE.jar!/:1.0.1.RELEASE]
    at org.springframework.cloud.config.server.JGitEnvironmentRepository.findOne(JGitEnvironmentRepository.java:80) ~[spring-cloud-config-server-1.0.1.RELEASE.jar!/:1.0.1.RELEASE]
    ... 70 common frames omitted
Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files: 
application.properties
...
...
    at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:416) ~[org.eclipse.jgit-3.5.3.201412180710-r.jar!/:3.5.3.201412180710-r]
    at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:397) ~[org.eclipse.jgit-3.5.3.201412180710-r.jar!/:3.5.3.201412180710-r]
    at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:261) ~[org.eclipse.jgit-3.5.3.201412180710-r.jar!/:3.5.3.201412180710-r]
    ... 73 common frames omitted
</pre>

**Comment by otrosien** [comment] 2016-05-24 07:35
I think this happens when you force-push into your config-repo.

**Comment by dsyer** [comment] 2016-05-24 07:42
Yes, either that or someone edited the working copy on the server?

**Comment by vishalmanohar** [comment] 2016-05-24 08:24
Hmm. Doesn't look like we did either.

**Comment by dsyer** [comment] 2016-05-24 13:56
Can you be a bit more specific about steps to reproduce then?

**Comment by vishalmanohar** [comment] 2016-05-25 01:21
@dsyer It happened only once over the last few weeks that we have been using the config server and we didn't do anything differently when this happened.

The set up is straight forward - multiple apps that listen to the config server -- which all start together during server start up. Will update if this happens again.

**Comment by wblancqu** [comment] 2016-09-20 06:59
Same occurred here...

Caused by: org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files:
application-cd.yml
application-docker.yml
        at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:265) ~[org.eclipse.jgit-3.5.3.201412180710-r.jar!/:3.5.3.201412180710-r]
        at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.checkout(JGitEnvironmentRepository.java:204) ~[spring-cloud-config-server-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
        at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.refresh(JGitEnvironmentRepository.java:148) ~[spring-cloud-config-server-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
        at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.getLocations(JGitEnvironmentRepository.java:121) ~[spring-cloud-config-server-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
        at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.getLocations(MultipleJGitEnvironmentRepository.java:111) ~[spring-cloud-config-server-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
        at org.springframework.cloud.config.server.environment.AbstractScmEnvironmentRepository.findOne(AbstractScmEnvironmentRepository.java:40) ~[spring-cloud-config-server-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
        at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.findOne(MultipleJGitEnvironmentRepository.java:146) ~[spring-cloud-config-server-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
        at org.springframework.cloud.config.server.environment.EnvironmentEncryptorEnvironmentRepository.findOne(EnvironmentEncryptorEnvironmentRepository.java:53) ~[spring-cloud-config-server-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
        at org.springframework.cloud.config.server.environment.EnvironmentController.labelled(EnvironmentController.java:112) ~[spring-cloud-config-server-1.1.2.RELEASE.jar!/:1.1.2.RELEASE]
        at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
        ... 56 more
Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files:
application-cd.yml

**Comment by tagae** [comment] 2016-09-20 07:42
This happened to me upon a forced push. Is there a way the config server can be configured to do a `git reset --hard <label>` and `git clean -fd` upon each refresh of the repo? or something along these lines that would avoid the kind of error described above?

**Comment by dsyer** [comment] 2016-09-20 10:31
#473 adds a flag `spring.cloud.config.server.git.forcePull`. Did you try that?

A lot of dirty repo problems have been reported to be caused by temp file cleaners in production servers (BSD and RHEL I think in particular). You can side step those by using an explicit `spring.cloud.config.server.git.basedir`.

**Comment by spring-issuemaster** [comment] 2018-10-02 17:00
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.

**Closed by spring-issuemaster** 2018-10-02 17:00 UTC
Labels: closable, question

**Comment by marecica2** [comment] 2021-04-19 12:53
Any thought on this we are experiencing this as well
whe have explicitly configured baseDir outside of /tmp

```
spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_ENDPOINT:https://our-bitbucket/scm/ic/configuration.git}
          username: ${GIT_USER}
          password: ${GIT_PWD}
          refresh-rate: 10
          force-pull: true
          clone-on-start: true
          default-label: ${DEFAULT_BRANCH:develop}
          delete-untracked-branches: true
          basedir: /git-repo
```
We dont squash commits or rewrite history neither force push on those target branches where the issue occurs 
The spring cloud config server is running in docker image  in k8s cluster
