### ISSUE TITLE
spring.profiles.include in Git configuration not adding the new profiles to the Spring Boot application

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-config#367] opened 2016-04-13 07:56 UTC
Several days ago I [submitted this question on Stackoverflow](http://stackoverflow.com/questions/36499360/spring-boot-spring-cloud-config-how-to-add-more-profiles-from-the-git-extern).

The idea is that in a Spring Boot application with Spring Cloud Config I would like to add some additional Spring profiles set in the Git repository.

@dsyer suggested using Spring Boot's 'spring.profiles.include' but I tested it and didn't work.

**Comment by pramit128** [comment] 2017-09-02 23:31
Is there any updated on this?

**Comment by spencergibb** [comment] 2017-09-03 00:19
No

**Comment by marcingrzejszczak** [comment] 2018-07-13 19:45
Is it still a problem with Finchley.RELEASE?

**Comment by spencergibb** [comment] 2018-10-01 22:37
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-10-01 22:37 UTC
Labels: waiting for feedback

**Comment by Grannath** [comment] 2018-12-07 14:52
@spencergibb I just tried this in Greenwich M3. I understand that it cannot be included in the first request, obviously. But the following boot sequence and all following updates of the config client only included the initial profile, not the included profile. So the problem persists.

There is an obvious workaround, to list all profiles explicitly. But it would be way easier to have one profile summarize the environment and then define that one in the git repo as a set of other profiles.

**Comment by ryanjbaxter** [comment] 2018-12-10 22:05
@Grannath @codependent indicated this was fixed after upgrading his boot version.  Can you provide a sample that reproduces the problem?
