### ISSUE TITLE
Config Server not fetching new remote branches

### ISSUE THREAD

**Issue by imberda** [spring-cloud/spring-cloud-config#439] opened 2016-07-09 08:57 UTC
There is currently an issue with the spring-cloud-config-server (1.1.0-RELEASE) when using a Git backed repository. The config-server does not allow getting config for remote branches added after the config-server initially clones the repository.

Steps to re-produce:
1. Start config server using remote Git repository
2. Make initial request to config server for existing branch (i.e. master)
3. Create a new branch in GitHub (e.g. new_branch)
4. Make a request to config-server for /some-app-name/default/new_branch

Expected behavior is the config for the "new_branch" is returned. Actual behavior is `NoSuchLabelException`.

The issue seems to stem from the fact that `JGitEnvironmentRepository` does not perform a fetch (`FetchCommand`) to find newly added branches created remotely, prior to attempting a checkout

This issue can _seem_ hard to re-produce if the config-server is being actively used and configuration is being requested for branches which are already known locally. This is because this causes a pull (`PullCommand`) which implicitly causes a fetch to occur.

This issue is likely the same (root cause) as #265, but I think this issue more succinctly describes the issue without other factors being involved.

As an aside, the rationale for wanting newly added remote branches to be found without a restart relates to the way the config-server is used within my development team. We have a single deployed instance of the config-server which all developers use as a shared service. Each developer starts whatever service they are working on locally (in their IDE) specifying a config-client  label to be their current feature branch. They then expect to be able to start their service and receive the config for that label.

**Comment by Krustie101** [comment] 2016-10-28 12:19
Somewhat related to this issue in its origin is a problem with moving tags in the repository. It might be possible to fix both issues in one go. In any case, the root cause is to be found in the refresh method of the JGitEnvironmentRepository.

1. Start server using a git repository with an existing tag.
2. Make initial request to config server for this existing tag.
3. Change configurations in the remote git repository and move the tag in the remote git repository to the new commit.
4. Make a subsequent request to the config server for this tag.

We expect that the new configurations will be loaded, but the old ones will be loaded because the tag is not moved in the git repository on the config server. In the refresh method, the checkout call for a tag returns a null ref, so that no pull is performed.

**Comment by rlynch** [comment] 2016-11-04 06:26
I have submitted a PR which I believe addresses this issue. #538

**Comment by spencergibb** [comment] 2016-11-28 17:19
Closed via 4c9806b4d699c5e27a9a62c5d1eeaf8029bbba47

**Closed by spencergibb** 2016-11-28 17:19 UTC
Labels: enhancement
